stm32-rs/stm32-rs

scripts/makecrates.py, stm32f0/src/lib.rs, stm32f1/src/lib.rs, stm32f2/src/lib.rs, stm32f3/src/lib.rs, stm32f4/src/lib.rs, stm32f7/src/lib.rs, stm32h7/src/lib.rs, stm32l0/src/lib.rs, stm32l1/src/lib.rs, stm32l4/src/lib.rs
ref: https://github.com/japaric/svd2rust/pull/206
=> replace macro_reexport with use_extern_macros

devices/stm32f0x0.yaml, devices/stm32f0x1.yaml, devices/stm32f0x2.yaml, devices/stm32f0x8.yaml, devices/stm32f100.yaml, devices/stm32f101.yaml, devices/stm32f102.yaml, devices/stm32f103.yaml, devices/stm32f107.yaml, devices/stm32f215.yaml, devices/stm32f217.yaml, devices/stm32f3x4.yaml, devices/stm32f3x8.yaml, devices/stm32f7x2.yaml, devices/stm32f7x3.yaml, devices/stm32f7x5.yaml, devices/stm32f7x6.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml, devices/stm32l0x1.yaml, devices/stm32l0x2.yaml, devices/stm32l0x3.yaml, devices/stm32l100.yaml, devices/stm32l151.yaml, devices/stm32l162.yaml, peripherals/pwr/pwr_f7.yaml, peripherals/pwr/pwr_v1.yaml, peripherals/pwr/pwr_v2.yaml
Maybe this can be more generic as other MCU might got this option too.
=> Add VOS enum.

Makefile
=> [#19] Use form to split device files into multiple folders

README.md, devices/stm32l100.yaml, scripts/svdpatch.py
Please see change in README for explination.
=> Added ability to split register fields

devices/common_patches/ethernet_macmiidr.yaml, devices/stm32f407.yaml, devices/stm32f427.yaml, devices/stm32f429.yaml, devices/stm32f469.yaml, devices/stm32f7x5.yaml, devices/stm32f7x6.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml, peripherals/eth/eth_mac.yaml
Fixes #69
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
=> Rename ETH_MACIIDR field TD to MD to align with RM0090

scripts/svdpatch.py
This is now checked for peripherals, interrupts, registers, and fields.
=> svdpatch: check for conflicts when adding items

README.md, scripts/svdpatch.py
=> svdpatch: allow deleting fields, registers, peripherals

devices/common_patches/ethernet_mac_regs.yaml, devices/common_patches/ethernet_macmiidr.yaml, devices/common_patches/f4_ethernet.yaml, devices/stm32f407.yaml, devices/stm32f427.yaml, devices/stm32f429.yaml, devices/stm32f469.yaml, devices/stm32f7x5.yaml, devices/stm32f7x6.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml, scripts/svdpatch.py
NOTE: This depends on #86 being merged to work!
=> Ethernet: fixup MACDBGR definition

.travis.yml, Makefile
This shows a failure in stm32l100 that seems legit...
=> travis: do a "cargo check" (no codegen) for all crates

devices/stm32l4x2.yaml, devices/stm32l4x3.yaml
I believe this fixes https://github.com/adamgreig/stm32-rs/issues/91
=> fix APB1ENR1.USBFSEN for l4x2 and l4x3

devices/stm32l4x5.yaml, devices/stm32l4x6.yaml
Hello,
I've created this pull request to address the issue #100 .
Let me know of any suggested modifications.
=> Update STM32L4x5/6 APB1ENR1 register fields

peripherals/rcc/rcc_f0.yaml
Documents some F0 family RCC registers.
=> F0 RCC registers

devices/stm32f0x0.yaml, devices/stm32f0x1.yaml, devices/stm32f0x2.yaml, devices/stm32f0x8.yaml, peripherals/rcc/rcc_f0.yaml, peripherals/rcc/rcc_f0x0.yaml, peripherals/rcc/rcc_f0x128.yaml
the f0x0 devices have a 1 bit PLLSRC, this patches that and updates the appropriate enum.
=> Stm32f0x0 PLLSRC

Makefile, scripts/htmlcomparesvdall.sh, scripts/svd2rust_install.sh, svd/extract.sh
This makes life easier for *BSD and NixOS users.
=> Makefile, *.sh: make path to bash more portable

devices/common_patches/f7_interrupts.yaml, devices/stm32f215.yaml, devices/stm32f217.yaml, devices/stm32f3x4.yaml, devices/stm32f401.yaml, devices/stm32f405.yaml, devices/stm32f407.yaml, devices/stm32f411.yaml, devices/stm32f412.yaml, devices/stm32f413.yaml, devices/stm32f427.yaml, devices/stm32f429.yaml, devices/stm32f446.yaml, devices/stm32f469.yaml, devices/stm32f7x2.yaml, devices/stm32f7x3.yaml, devices/stm32f7x5.yaml, devices/stm32f7x6.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml
Rebase some I2C, SPI and USART peripherals for more uniformity across devices.
=> Rebase a few more peripherals

devices/stm32f103.yaml, peripherals/tim/tim_ccr.yaml
As PR #167 will not be accepted soon, please merge this revert before 0.7.
=> rm tim ccr 103 (revert)

README.md
* seprate -> separate
* heirarchy -> hierarchy
* targetting -> targeting
* enumuerated -> enumerated
=> a couple of spelling fixes

scripts/makecrates.py, stm32f0/Cargo.toml, stm32f1/Cargo.toml, stm32f2/Cargo.toml, stm32f3/Cargo.toml, stm32f4/Cargo.toml, stm32f7/Cargo.toml, stm32g0/Cargo.toml, stm32h7/Cargo.toml, stm32l0/Cargo.toml, stm32l1/Cargo.toml, stm32l4/Cargo.toml
This might also require a version change of all sub component. Let me know.
=> Use cortex-m latest 0.6.0

devices/common_patches/l0_tim.yaml, devices/stm32l0x1.yaml, peripherals/dbg/dbg_l0.yaml, peripherals/exti/exti_v1.yaml, peripherals/gpio/gpio_l0.yaml, peripherals/rcc/rcc_l0.yaml, peripherals/tim/tim21.yaml, peripherals/tim/tim_l0.yaml
Updated timer registers, added debug registers, and made minor patches to other fields.
=> Updated patches for L0 family

scripts/makehtml.index.template.html, scripts/makehtml.py
=> Include links to patched SVDs in HTML output

devices/stm32h7x3.yaml
=> stm32h7x3: Ethernet_DMA.DMAMR.INTM is 2 bit wide

devices/stm32g0x0.yaml, devices/stm32g0x1.yaml
=> STM32G0: DMA patch

devices/common_patches/f0_comp_common.yaml, devices/common_patches/f3_comp246.yaml, devices/common_patches/f3_opamp2.yaml, devices/common_patches/f7_dbgmcu.yaml, devices/common_patches/h7_dbgmcu.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml, scripts/svdpatch.py
This should close #227.
But I'm not sure about syscfg+comp+opamp.
These peripherals occupy one memory block but work independently.
=> svd 0.7 compatibility

devices/stm32h7x3.yaml, peripherals/adc/adc_h7_revision_y.yaml, peripherals/adc/adc_v3.yaml, peripherals/adc/adc_v3_multi.yaml
Definitions and fixes for ADC
For H742/743/750/753 Revision Y ('current' silicon), although Revision Y
specifics are broken out into a separate file.
Written against RM0433 Rev 6 04-Apr-2019
=> stm32h7x3: ADC

devices/stm32h7x3.yaml, devices/stm32l0x1.yaml, peripherals/lptim/lptim_v1.yaml
@arkorobotics's L0 LPTIM definitions apply to H7 also
=> stm32h7x3: LPTIM

README.md, devices/stm32f411.yaml, devices/stm32l4x5.yaml, scripts/interrupts.py, scripts/svdpatch.py
* Adds ability to modify and delete interrupts from peripherals
* Adds missing STM32F411 interrupts
Closes #163 and #136 and #255. Replaces #170.
=> Interrupt fixes

.gitignore, .travis.yml, Makefile, scripts/makecrates.py, stm32f0/src/lib.rs, stm32f1/src/lib.rs, stm32f2/src/lib.rs, stm32f3/src/lib.rs, stm32f4/src/lib.rs, stm32f7/src/lib.rs, stm32g0/src/lib.rs, stm32g4/src/lib.rs, stm32h7/src/lib.rs, stm32l0/src/lib.rs, stm32l1/src/lib.rs, stm32l4/src/lib.rs
Add support of new svd2rust.
Depends on https://github.com/rust-embedded/svd2rust/pull/362
=> generics, svd2rust 0.16

Makefile, rustfmt.toml
Unfortunately this feature still unstable (nightly rustfmt).
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#normalize_doc_attributes
=> normalize-docs

scripts/makehtml.py
This makes makehtml.py work with `bitRange` as well as `bitOffset`/`bitWidth` - `bitRange` is used in some non ST svd files.
Additionally, on Windows `multiprocessing.Pool` behaves differently - it spawns a new process for each worker, meaning that globals (`args`) aren't available, using a `ThreadPool` instead mitigates this and is more suitable as this should be IO bound, not CPU bound.
=> Make makehtml.py work with bitRange and on Windows

devices/common_patches/2_nvic_prio_bits.yaml, devices/common_patches/3_nvic_prio_bits.yaml, devices/stm32g030.yaml, devices/stm32g031.yaml, devices/stm32g041.yaml, devices/stm32g07x.yaml, devices/stm32g081.yaml
@adamgreig could you review and merge this PR?
=> Fix priority bits on G0 family

peripherals/usart/uart_common.yaml
=> uart_common: fix a typo

devices/common_patches/dma/dma2d_v2.yaml, devices/stm32f469.yaml, devices/stm32f745.yaml, devices/stm32f765.yaml, devices/stm32f7x6.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml, devices/stm32h743.yaml, devices/stm32h743v.yaml, devices/stm32h747cm4.yaml, devices/stm32h747cm7.yaml, devices/stm32h753.yaml, devices/stm32h753v.yaml, devices/stm32l4x6.yaml, peripherals/dma/dma2d_common.yaml, peripherals/dma/dma2d_v1.yaml, peripherals/dma/dma2d_v2.yaml
On F469 and H7. Small patch for H7 registers also.
=> Partial documentation for DMA2D (aka. "Chrom-Art Accelerator")

devices/stm32f410.yaml
Signed-off-by: Aurabindo Pillai <mail@aurabindo.in>
=> Add missing interrupts for USART

devices/stm32f410.yaml
* Add interrupt definitions
* Put value of description field in double quotes for formatting consistency
=> stm32f410: add remaining interrupts

devices/common_patches/usb_otg/otg_hs_fixes_v1.yaml
`make patch` did not work for me, complaining about description of STALL. This PR solved it for me.
(Or is it some compat issue? I'm on Windows, x64, python 3.7.)
=> minor fix ('make patch' did not work)

devices/stm32f401.yaml, devices/stm32f405.yaml, devices/stm32f407.yaml, devices/stm32f411.yaml, devices/stm32f412.yaml, devices/stm32f413.yaml, devices/stm32f427.yaml, devices/stm32f429.yaml, devices/stm32f469.yaml, peripherals/sdio/sdio_f4.yaml
Documentation and limits for the sdio register values.
=> Update stm32f4 SDIO register fields and values

devices/common_patches/g0_dma_5ch.yaml, devices/common_patches/g0_dma_7ch.yaml, devices/stm32g030.yaml, devices/stm32g031.yaml, devices/stm32g041.yaml, devices/stm32g070.yaml, devices/stm32g071.yaml, devices/stm32g081.yaml, peripherals/exti/exti_g0.yaml
- removal of peripherals that are not present on G070 and G071
- fix register offset bug in EXTI
=> Fixes for G070, G071, G081

devices/stm32f3x8.yaml
=> Add missing GPIO bits to stm32f3x8

devices/common_patches/h7_common_singlecore.yaml, devices/common_patches/h7_dmacr.yaml, devices/stm32h743.yaml, devices/stm32h743v.yaml, devices/stm32h747cm7.yaml, devices/stm32h753.yaml, devices/stm32h753v.yaml, devices/stm32h7b3.yaml
=> stm32h7: Add missing TRBUFF bit

peripherals/tim/tim_basic.yaml
=> Fixed spelling mistake

peripherals/i2c/i2c_v2_without_wakeup.yaml
=> Fix typo in i2c_v2_without_wakeup.yaml

devices/common_patches/sdio_f446.yaml, devices/stm32f446.yaml, peripherals/sdio/sdio_f4.yaml, peripherals/sdio/sdio_f446.yaml, peripherals/sdio/sdio_f4_common.yaml, scripts/makehtml.py
For some reason SVD file is significantly different from what the reference manual says. 
Since some of the fields are presumably common across different F4 implementations of this peripheral, I've tried to DRY the descriptions where applicable.
=> STM32F446 SDIO

devices/stm32h7b3.yaml, peripherals/dma/dmamux_v1.yaml
Terrible hack to change the evaluation order
=> Enable dmamux patch for stm32h7b3 parts

devices/stm32f401.yaml, devices/stm32f410.yaml, devices/stm32f411.yaml, devices/stm32f412.yaml, devices/stm32f413.yaml
a patch to patch SMPRx registers for all stm32f4
=> patch smpr register for all f4

devices/stm32f413.yaml
=> Patch stm32f413 to include OTG_FS interrupt.

scripts/makecrates.py, stm32_part_table.yaml
We sure have a lot of stm32g0 parts now!
=> Update g0 parts in parts table and docs.rs features

devices/common_patches/g4_rcc.yaml, devices/stm32g431.yaml, devices/stm32g441.yaml, devices/stm32g471.yaml, devices/stm32g473.yaml, devices/stm32g474.yaml, devices/stm32g483.yaml, devices/stm32g484.yaml, devices/stm32g491.yaml, peripherals/rcc/rcc_g4.yaml
Heya! 
Adding a few new enum fields to the G4 RCC. Let me know if there's a better place to organize/put these. 
Note: I only have access to the STM32G474, but I suspect that these enumerations are common across the G4 family seeing as the only differences appear to be RAM/ROM; they all share the same max frequency AFAICT.
=> Added some new enumerations for G4's RCC

Makefile, scripts/htmlcomparesvd.py, scripts/htmlcomparesvdall.sh, scripts/makehtml.index.template.html, scripts/makehtml.template.html
Also cleaned up the HTML a bit.
=> Build peripheral comparisons pages as part of html target

peripherals/syscfg/syscfg_wl.yaml
=> Fix STM32WL EXTI14 using values for EXTI15

devices/common_patches/h7_rcc_src_sel.yaml, devices/common_patches/h7_rcc_src_sel_common.yaml, devices/stm32h735.yaml
=> H735: fix conflicting rules and one duplicate rule

devices/common_patches/f745_f750_f765_f7x6_f7x7_f7x9_common.yaml, devices/common_patches/f745_f750_f765_f7x6_f7x7_f7x9_sdmmc.yaml
Following #613, fix fields in SDMMC* for every F7 chips
=> [stm32f7] Fix SDMMC registers

devices/common_patches/stm32l4x2_l412.yaml, devices/stm32l4x1.yaml, devices/stm32l4x5.yaml
Various SVD fixes to L4 chips.
=> Fix wrong bit offset of CRCEN/CRCRST/CRCSMEN and USARTXSMEN for L4 family

CHANGELOG.md, README.md, scripts/makecrates.py
Closes #619. I plan to get #637 in, have a brief check over recent open issues, then release this today or tomorrow. Sorry for the wait!
=> Prepare for v0.14.0 release

CHANGELOG.md, devices/common_patches/f765_f7x7_f7x9_common.yaml
Fix https://github.com/stm32-rs/stm32-rs/issues/655.
=> Add SDMMC2EN and SDMMC2RST to F765, F7x7, F7x9

.github/workflows/ci.yaml
As documented [here](https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners) and also discussed [here](https://github.com/actions/virtual-environments/issues/1757)
=> Run sudo apt-get update before installing a package

devices/common_patches/fpu_interrupt.yaml, peripherals/rcc/rcc_f0.yaml
Cosmetic changes - one typo and one re-alignment with other descriptions.
=> Description fixes

CHANGELOG.md, Makefile
related feature in svd2rust
https://github.com/rust-embedded/svd2rust/pull/591
=> Use PascalCase for values of enums

.github/workflows/gh-pages.yaml
Currently failing: https://github.com/stm32-rs/stm32-rs/actions/runs/2324401052
=> ci: fix github pages build

devices/common_patches/h7_common_highmemory.yaml, devices/stm32h735.yaml
RM0468:
Base address RM0468 Rev 2 page 137
Interrupt offset RM0468 Rev 2 page 741
RM0455:
Base address RM0455 Rev 6 page 133
Interrupt offset RM0455 Rev 6 page 722
=> H7: Add UART9/USART10 for RM0468 parts, fix base address for RM0455 parts

.github/workflows/mmaps_master.yaml, .github/workflows/mmaps_pr.yaml
Closes #756 hopefully.
cc @burrbull
=> ci: fix path to tool_install.sh for mmaps actions

.github/workflows/nightlies.yaml
=> ci: fix tool install for nightlies

devices/stm32f405.yaml, devices/stm32f413.yaml, devices/stm32f427.yaml, devices/stm32f429.yaml, devices/stm32f469.yaml
=> F4 uart derivation interrupt fixes

devices/common_patches/ramecc/ramecc.yaml
See https://github.com/stm32-rs/svdtools/pull/128
=> fix ramecc _delete fields

README.md
fix copy paste error STM32H**7** -> STM32H**5**
=> minor fixup in readme

CHANGELOG.md, Makefile, README.md, scripts/tool_install.sh
yet another oxidized tool
possibly related to #807 
cc @newAM
=> Replace makehtml.py with svd2html

devices/common_patches/sai/sai_v2.yaml, peripherals/sai/sai.yaml
should not have change in mmaps
=> sai reorder rules

devices/common_patches/h5.yaml, devices/stm32h503.yaml, devices/stm32h562.yaml, devices/stm32h563.yaml, devices/stm32h573.yaml
This is a WIP. Currently, the changes in it, eg removing underscores on registers, is not working; open to ideas. Likely many more patches to apply after that part is fixed.
Edit: Per a discussion with Burbull, it seems the changes are taking on the GH "Memory map comparison" build, but not on my machine.
=> H5 patches

.github/workflows/cargo-make.yaml, .github/workflows/ci.yaml, .github/workflows/mmaps_pr.yaml
Add CI for cargo-make support, run normal checks on push to master, force push PR mmaps to avoid conflicts after rebase
=> CI updates

peripherals/rtc/rtc_common.yaml
set variant for `MT` field of `DR` register and `TSDR` register
will close #828
=> set variant for `MT` field

Makefile, README.md
=> Update README instructions around extracting SVDs

CHANGELOG.md, devices/common_patches/bkp/bkp.yaml, devices/common_patches/dma/dmamux_array.yaml, devices/common_patches/hash/hash.yaml, devices/common_patches/hsem/array.yaml, devices/common_patches/rtc/wl.yaml, devices/common_patches/tim/tim_ccr.yaml
needed for https://github.com/rust-embedded/svdtools/pull/178
=> fix array descriptions

CHANGELOG.md, devices/stm32g491.yaml
=> Add FDCAN2 peripheral to G491

CHANGELOG.md, devices/stm32g491.yaml
A bug introduced in my last pr.
=> Fix key in patch

CHANGELOG.md, devices/collect/flash/secbbr.yaml, devices/collect/hsem/r.yaml, devices/collect/jpeg/ram.yaml, devices/collect/rtc/alarm.yaml, devices/collect/rtc/alarm_wl.yaml, devices/collect/sdio/resp.yaml, devices/common_patches/dma/g4_ifcr.yaml, devices/stm32f103.yaml, devices/stm32g431.yaml, devices/stm32g441.yaml, devices/stm32g471.yaml, devices/stm32g473.yaml, devices/stm32g474.yaml, devices/stm32g483.yaml, devices/stm32g484.yaml, devices/stm32g491.yaml, devices/stm32g4a1.yaml
=> G4 DMA IFCR & more array descriptions

CHANGELOG.md, devices/stm32f103.yaml
Blocks https://github.com/rust-embedded/svdtools/pull/178
=> fix F103 USB RESP1

CHANGELOG.md, devices/collect/dsi/isr.yaml, devices/collect/sai/pdm.yaml, devices/stm32f469.yaml, devices/stm32f765.yaml, devices/stm32f7x7.yaml, devices/stm32f7x9.yaml, devices/stm32g431.yaml, devices/stm32g441.yaml, devices/stm32g471.yaml, devices/stm32g473.yaml, devices/stm32g474.yaml, devices/stm32g483.yaml, devices/stm32g484.yaml, devices/stm32g491.yaml, devices/stm32g4a1.yaml, devices/stm32h735.yaml, devices/stm32h743.yaml, devices/stm32h743v.yaml, devices/stm32h747cm4.yaml, devices/stm32h747cm7.yaml, devices/stm32h753.yaml, devices/stm32h753v.yaml, devices/stm32h7b3.yaml, devices/stm32l4r9.yaml, devices/stm32l552.yaml, devices/stm32l562.yaml, devices/stm32mp157.yaml, devices/stm32wb55.yaml
=> Field array: DSI, SAI

CHANGELOG.md, devices/collect/dma/bdma.yaml, devices/collect/dma/h7_dmamux.yaml, devices/collect/dma/isr_array.yaml, devices/collect/dma/mdma.yaml, devices/collect/dma/v1.yaml
=> field-arrays: DMA

CHANGELOG.md, scripts/tool_install.sh
See [Cargo Home](https://doc.rust-lang.org/cargo/guide/cargo-home.html) in the Cargo Book
=> tools_install: support $CARGO_HOME environment variable

CHANGELOG.md, devices/common_patches/gpdma/gpdma.yaml, devices/common_patches/h5.yaml, devices/stm32h503.yaml, devices/stm32h562.yaml, devices/stm32h563.yaml, devices/stm32h573.yaml, peripherals/gpdma/gpdma.yaml
As far as I'm aware, the GPDMA is new for the H5 family. This adds all the register field definitions for the GPDMA on the H5.
=> Add GPDMA peripheral for H5

CHANGELOG.md, devices/collect/comp/csr.yaml, devices/common_patches/comp/g4.yaml, devices/stm32g431.yaml, devices/stm32g441.yaml, devices/stm32g471.yaml, devices/stm32g473.yaml, devices/stm32g474.yaml, devices/stm32g483.yaml, devices/stm32g484.yaml, devices/stm32g491.yaml, devices/stm32g4a1.yaml
=> G4:COMP fix and collect array

CHANGELOG.md, devices/common_patches/rcc/g0.yaml, devices/common_patches/rcc/g0_no_aes.yaml, devices/common_patches/rcc/g0b.yaml, devices/common_patches/rcc/g0x0_delete.yaml, devices/stm32g030.yaml, devices/stm32g031.yaml, devices/stm32g041.yaml, devices/stm32g050.yaml, devices/stm32g051.yaml, devices/stm32g061.yaml, devices/stm32g070.yaml, devices/stm32g071.yaml, devices/stm32g081.yaml, devices/stm32g0b0.yaml, devices/stm32g0b1.yaml, devices/stm32g0c1.yaml, peripherals/rcc/rcc_g0.yaml, peripherals/rcc/rcc_g0_common.yaml, peripherals/rcc/rcc_g0b.yaml, peripherals/rcc/rcc_g0b1.yaml, peripherals/rcc/rcc_g0x1.yaml, peripherals/rcc/rcc_g0x1_aes.yaml, peripherals/rcc/rcc_g0x1_cec.yaml, peripherals/syscfg/syscfg_g0_common.yaml, peripherals/syscfg/syscfg_g0_usart2.yaml, peripherals/syscfg/syscfg_g0_usart4.yaml
This is based on #947, so it can't be merged until that is.
=> Cover more G0 peripheral fields

CHANGELOG.md, devices/common_patches/fdcan/fdcan_g4.yaml
=> Fix G4 interrupt numbers

CHANGELOG.md, devices/stm32g471.yaml
Hopefully the last PR for now :)
=> G471 Add OPAMP6

CHANGELOG.md, peripherals/rcc/rcc_g0_common.yaml
`Div3` actually divides frequency by 4.
=> Fix typo in g0 RCC HSIDIV

CHANGELOG.md, devices/common_patches/hrtim/strip.yaml, devices/common_patches/hrtim/v1.yaml, devices/common_patches/hrtim/v2.yaml, peripherals/hrtim/hrtim.yaml
=> HRTIM: remove timer block suffixes

CHANGELOG.md, devices/collect/hrtim/f3.yaml, devices/collect/hrtim/h7.yaml, devices/collect/hrtim/v1.yaml, devices/common_patches/hrtim/v1.yaml, devices/common_patches/hrtim/v2.yaml, peripherals/hrtim/hrtim.yaml
@burrbull , again thanks for this!
~~I have only gone through this yet(slowly going through the rest)~~ - Done
=> HRTIM: SET/RST

devices/common_patches/hrtim/v2.yaml
=> fix RSTR::TIMCMP

devices/stm32h503.yaml, devices/stm32h562.yaml, devices/stm32h563.yaml, devices/stm32h573.yaml, peripherals/iwdg/h5.yaml, peripherals/iwdg/iwdg.yaml
=> fix IWDG PR

CHANGELOG.md, devices/common_patches/h7_common_dualcore.yaml, devices/common_patches/h7_common_highmemory.yaml, devices/common_patches/hrtim/h7.yaml, peripherals/hrtim/common.yaml
=> H7's HRTIM does not have DLL

CHANGELOG.md, devices/stm32h503.yaml, devices/stm32h562.yaml, devices/stm32h563.yaml, devices/stm32h573.yaml
Array-ify H5 gpio register fields
=> H5 - GPIO array's

CHANGELOG.md, devices/collect/gtzc/h5_u5.yaml, devices/stm32h503.yaml, devices/stm32h562.yaml, devices/stm32h563.yaml, devices/stm32h573.yaml, devices/stm32l552.yaml, devices/stm32l562.yaml, devices/stm32u535.yaml, devices/stm32u545.yaml, devices/stm32u575.yaml, devices/stm32u585.yaml, devices/stm32u595.yaml, devices/stm32u599.yaml, devices/stm32u5a5.yaml, devices/stm32u5a9.yaml
=> gtzc1 arrays

CHANGELOG.md, devices/patches/tim/tim_ccrx_16bit.yaml, devices/stm32g0b0.yaml, devices/stm32g0b1.yaml, devices/stm32g0c1.yaml
=> TIM3 ccrx is 16 bit on G0Bx and G0C1

CHANGELOG.md, devices/stm32g471.yaml, devices/stm32g473.yaml, devices/stm32g474.yaml, devices/stm32g483.yaml, devices/stm32g484.yaml
Fixes issue described in #957 
This is my first time delving into svd file so not sure if I'm doing this correctly.
=> Fix resetValue of g4 SPI4 CR1 and CR2

CHANGELOG.md, devices/collect/dma/gpdma/h5.yaml, devices/collect/dma/gpdma/h7rs_u5.yaml, devices/collect/dma/hpdma.yaml, devices/fields/tim/tim_16bit.yaml, devices/fields/tim/tim_32bit.yaml
~~Waiting for svd2rust release~~
=> DMA cluster derive

devices/patches/sai/fsdef-rw.yaml, devices/patches/sai/h7.yaml, devices/stm32h562.yaml, devices/stm32h563.yaml, devices/stm32h573.yaml, devices/stm32h7r.yaml, devices/stm32h7s.yaml, devices/stm32mp153.yaml, devices/stm32mp157.yaml, devices/stm32n645.yaml, devices/stm32n647.yaml, devices/stm32n655.yaml, devices/stm32n657.yaml, devices/stm32u535.yaml, devices/stm32u545.yaml, devices/stm32u575.yaml, devices/stm32u585.yaml, devices/stm32u595.yaml, devices/stm32u599.yaml, devices/stm32u5a5.yaml, devices/stm32u5a9.yaml
As usual, I dont quite know what I am doing :)
=> SAI - fsdef is rw

CHANGELOG.md, README.md
I think it's probably time! Please comment any open issues or PRs that should be included before 0.16.
=> Prepare for v0.16.0

CHANGELOG.md, devices/stm32f767.yaml, devices/stm32f777.yaml, devices/stm32l412.yaml
=> Fix L412 RTC interrupts
