- README.md
- peripherals/adc/adc_v2.yaml
- peripherals/crc/crc_basic.yaml
- peripherals/gpio/gpio_v2.yaml
- peripherals/rcc/rcc_v2.yaml
- peripherals/spi/spi_common.yaml
- peripherals/spi/spi_v2.yaml
- scripts/svdpatch.py
The previous YAML format didn't support separate enumerated values for read and write usage.  This is required e.g. here http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0553a/Cihcajhj.html
I updated the peripheral yaml files that used the old format and the README example.  There was also quite a funny typo in the README :hankey: :scream: :see_no_evil:
> Updated YAML format to support different enumerated values for R/W

- peripherals/gpio/gpio_v2.yaml
`fnname` doesn't seem to support `([0-9]|1[0-5])` regex, so I couldn't think of any more elegant solution than copying the descriptions.
> fix matching of LCKR fields in GPIO_v2

- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- peripherals/iwdg/iwdg.yaml
Documents the IWDG fields and add it to the devices of the STM32F0 familly.
> Add IWDG peripherals to the stm32f0xx family

- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- peripherals/crc/crc_advanced.yaml
- peripherals/crc/crc_with_polysize.yaml
Extends the basic CRC with reversal mode fields. This peripheral is used in at least the STM32F0 familly. Not all devices have this mode but it seems there is only on svd files per family. So it describe registers and fields that doesn't appear in all devices.
I have documented the POLYSIZE field has well, but I don't know where to put it. Is storing it on `crc_with_polysize.yaml` and include it on the devices that has it seems a good ideas? Please let me know.
> Add advanced CRC peripheral

- devices/common_patches/gpio_with_OSPEEDER.yaml
- devices/stm32l100.yaml
- devices/stm32l151.yaml
- devices/stm32l162.yaml
This patches the typo and allows the general GPIO patch 'gpio_v2.yaml'. This also fixes issue #53.
> Patching typo on the STM32L chips

- scripts/htmlcomparesvd.py
Helps a lot when searching on which family peripheral exists. CSS only implementation. Tested on firefox.  
The styling can be improve, but first let me know if that seems a good idea.
> Add a sticky header and first columns to Peripheral Compare page

- .gitignore
- Makefile
- scripts/makehtml.py
Makehtml.py now only generates the html if there is not an associated html file or if the svd is newer. This is because the 'make html' target is much faster than the svd2rust target and is good for quickly checking your work. Now you can do it faster. I also added in a few corrections to the Makefile, such as PHONY designation.
> Adding some smarts to 'make html'

- devices/common_patches/rcc_LSECSSC_LSECSSF.yaml
- devices/stm32l100.yaml
- peripherals/exti/exti_v1.yaml
- peripherals/rcc/rcc_l1.yaml
Adding documentation. Note this relies on pull request #60. It is presented as two separate pull request for simplicity. This serves to fully document the RCC and EXTI peripherals for the STM32L100. The only register that was not documented was the trimming register because I do not think I understand the documentation.
> Documented RCC and EXTI for STM32L100

- devices/stm32h7x3.yaml
Rename registers to make them like any others STM32 family. All STM32 has a described WWDG peripherals.
> H7 family has WWDG peripheral

- devices/common_patches/f4_ethernet.yaml
- devices/stm32f407.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f469.yaml
Except for STM32F469/479 all Ethernet peripeherals are described as
identical in RM0090 so this change makes sure that all existing patches
for the F407 are applied to the rest of the family as well for
consistency.
Fixes #70.
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Align Ethernet peripheral patches for the whole F4 family

- devices/common_patches/f0_adc_cfgr2_ckmode.yaml
- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
This fixes misnamed fields in ADC CFGR2 for all stm32f0.
The fields JITOFF_D2 and JITOFF_D4 don't exist in the stm32l0 reference manual, which instead contains a CKMODE field.
This CKMODE field is the same as in stm32l0 (for which svd files are correct).
> f0: replace JITOFF_D* by CKMODE in ADC CFGR2 to match RM0360 and RM0091

- devices/stm32f429.yaml
This is ported from a similar PR I made to the `stm32f429` crate. Your version of patching SVDs is much nicer :)
The only things now missing compared to their SVD patch is:
* descriptions for the MAC registers - you already have descriptions for the individual bits though
I guess I can add these to the global MAC yaml?
* a DEVICE_ID peripheral to read out the three unique ID words at 0x1FFF7A10
Do you want to have this included? It's probably relevant to all STMs?
> stm32f429: add missing RCC reset/enable bits

- peripherals/eth/eth_dma.yaml
- peripherals/eth/eth_mac.yaml
- peripherals/eth/eth_mmc.yaml
This is purely docstrings. There are, however, two things I have noticed that require renamings (using the STM32F429 ref. manual as the authority):
* `RAM` in `MACFFR` should be `PAM` (Pass all multicast)
* The fields in `MACDBGR` are completely wrong - they seem to be copied from `ETH_MMCCR`.
What is the approach to such changes?
> eth_mac: add field descriptions

- stm32l4/Cargo.toml
Generally, would make sense to align documented devices with availability of Nucleo boards.
> Change `package.metadata.docs.rs` for stm32l4

- devices/stm32l4x2.yaml
I hope this is correct!
- strangely, stm32l4x3 is not affected by https://github.com/adamgreig/stm32-rs/issues/37
- I renamed the entire peripheral to just `USB` as this is what both l4x3 and f103 do (considering the latter because I will port `mvirkkunen/stm32f103xx-usb`)
- the interrupt was listed under `USB_FS`, it is missing from both l4x3 and f103...
- I don't know if the previous baseAddress `0x4000_6C00` is needed anywhere?
- regarding the `USB_{ADDR,COUNT}n_{TX,RX}` registers, both l4x3 and f103 don't seem to have them; the `usb-device` implementation seems to hardcode it (https://github.com/mvirkkunen/stm32f103xx-usb/blob/master/src/endpoint.rs#L49) - I may send a separate PR if it makes sense to patch them in
> attempt to fix USB peripheral for stm32l4x2

- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- peripherals/rcc/rcc_f0.yaml
If I understand things correctly (which I'm not exactly confident about :wink:), this should add support for the `APB2ENR` and `APB1ENR` registers for the STM32F0 series of devices.
This information was pulled from the reference for the [STM32F0X0 devices](https://www.st.com/content/ccc/resource/technical/document/reference_manual/cf/10/a8/c4/29/fb/4c/42/DM00091010.pdf/files/DM00091010.pdf/jcr:content/translations/en.DM00091010.pdf) specifically.
`APB2ENR` is missing `USART6EN`, and `APB1ENR` is missing `USBEN`, as they threw errors during compilation and frankly I don't understand the project well enough how to fix it yet.
Let me know if this is correct and/or if any changes need to be made. If I messed it up I can always give it another go. Thanks for all the hard work that has gone …
> Reset and clock control for AHB/APB peripherals on stm32f0

- README.md
- devices/stm32f401.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f410.yaml
- devices/stm32f411.yaml
- devices/stm32f412.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
- scripts/svdpatch.py
This is the implementation of my idea in #97.
Specify in a device yaml as follows (I'm sure this can be improved, just not sure how):
```yaml
_rebase:
I2C1: I2C3
```
It was a coin toss as to when the rebase occurs, before or after modifying peripherals.
> Allow rebasing peripherals

- peripherals/usart/uart_uart.yaml
On UART (contrary to USART), the 2 bits stop field of CR2 only accept values 0b00 (1 stop bit) or 0b10 (2 stop bits). So basically, this is actually a 1 bit field.
The currently defined value for Stop2 is incorrect for a 2 bits fields, it should be 2 instead of 1.
This patch actually changes the stop field to only 1 bit, making the value of Stop2 correct, and changing the unsafe .bits() method to a safe .bit() method.
> Fix handling of UART stop bit on STM32F4

- README.md
- devices/stm32f103.yaml
This is actually all I could find in the stm32f103xx patch file related to USB; I'm not sure if it will be enough to fix the issues you were having @therealprof? I think `USBPRE` was the main one?
If this is enough I'd like to get 0.5 released ASAP with svd2rust 0.14 support; we can always add more of the stm32f103xx patches later too. I think combined with the new array support from #107 we should be good for USB on STM32F103 at least, which will hopefully enable stm32f103xx-usb to work too. @mvirkkunen?
> STM32F103 USB patches

- devices/common_patches/f0_usart6.yaml
- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- peripherals/rcc/rcc_f0.yaml
This is mostly just cleaning up the changes I made in #99 
`DMAEN` was moved into the common `rcc_f0.yaml` file rather than being repeated in each individual device file, and I created a common patch for the `USART6` peripheral on F0-series devices.
> USART6 common patch for STM32F0, move DMAEN from device to rcc_f0.yaml peripheral file

- Makefile
rustfmt will recurse through submodules itself.
This is required with new version of `form` which generate modules as xxx.rs instead of xxx/mod.rs.
> Makefile: simplify rustfmt call

- devices/common_patches/f0_syscfg.yaml
- devices/common_patches/f0_syscfg_common.yaml
- devices/common_patches/f0_syscfg_comp.yaml
- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- peripherals/comp/comp_f0.yaml
- peripherals/syscfg/syscfg_f0.yaml
- peripherals/syscfg/syscfg_f0x128.yaml
- remove fields that are not present on stm32f0x0
- rename fields that don't match the Reference Manual
- split SYSCFG_COMP into SYSCFG and COMP to match Reference Manual
- document all fields
Fix #122
> Cleanup and document STM32F0 SYSCFG and COMP registers

- scripts/makecrates.py
* updated links that were redirecting from old repo
* fixed broken device crate links that wern't working because of case sensitivity
* added markdown to generated doc strings so we can get links in the docs
> Docupdates

- .travis.yml
- Makefile
Make the `make check` invocation run linearly (`-j1`) but with a common target dir to prevent rebuilding of deps.
> Faster Travis Builds

- devices/common_patches/f2_rcc.yaml
- devices/stm32f215.yaml
- devices/stm32f217.yaml
This is just a very quick pass at stm32f2 RCC. It is probably not exhaustive, and I may have a deeper look at stm32f2 later on. Still I think this quick PR should already be quite useful and I thought it might be worth considering if you want to make a release.
> Rcc documentation for stm32f2

- devices/common_patches/l0_flash.yaml
- devices/common_patches/l0_pwr_mode.yaml
- devices/common_patches/l0_rtc.yaml
- devices/common_patches/l0_syscfg_cfgr.yaml
- devices/common_patches/remove_l0_mpu.yaml
- devices/common_patches/remove_l0_scb.yaml
- devices/common_patches/remove_l0_stk.yaml
- devices/stm32l0x1.yaml
- devices/stm32l100.yaml
- peripherals/adc/adc_l0.yaml
- peripherals/aes/aes_l0.yaml
- peripherals/crc/crc_l0.yaml
- peripherals/exti/exti_l0.yaml
- peripherals/flash/flash_l0.yaml
- peripherals/fw/fw_l0.yaml
- peripherals/gpio/gpio_l0.yaml
- peripherals/lptim/lptim_l0.yaml
- peripherals/mpu/mpu_v1.yaml
- peripherals/nvic/nvic_v1.yaml
- peripherals/pwr/pwr_l0.yaml
- peripherals/rcc/rcc_l0.yaml
- peripherals/rcc/rcc_l0_l1_common.yaml
- peripherals/rcc/rcc_l1.yaml
- peripherals/rtc/rtc_l0.yaml
- peripherals/spi/spi_l0.yaml
- peripherals/syscfg/syscfg_l0.yaml
- peripherals/tim/tim21.yaml
- peripherals/tim/tim_l0.yaml
This PR contains the requested changes from PR #126 (which failed to merge cleanly) and the remaining peripherals required to complete coverage of the L0 family.
> Updated L0 family to include all available perpherials

- stm32_part_table.yaml
- stm32f3/README.md
STM32F318 is documented in RM0366 and not in RM0316 so it should use
the stm32f301 module.
STM32F378 is documented in RM0313 and not in RM0316 so it should use
the stm32f373 module.
Also the st.com links for stm32f373 and stm32f3x8 where inverted.
> Fix stm32f3 README about what module to use for STM32F318 and STM32F378

- devices/stm32h7x3.yaml
> stm32h7x3: strip PWR_ prefix in PWR registers

- devices/stm32h7x3.yaml
It's "read-set" according to the RM. Definitely writable.
> stm32h7x3/SPI: CSTART is read-write

- devices/stm32f0x2.yaml
According to the reference manual chapter 11.1.3 the
interrupt vector positions 9-12 should be:
- 9 - DMA_CH1
- 10 - DMA_CH2_3
- 11 - DMA_CH4_5_6_7
- 12 - ADC_COMP
but positions 10 and 11 are missing in the .svd.
> Add missing DMA interrupts for stm32f0x2

- devices/common_patches/f0_comp_common.yaml
- devices/common_patches/f0_syscfg_comp.yaml
- devices/common_patches/f3_comp1234567.yaml
- devices/common_patches/f3_comp1246.yaml
- devices/common_patches/f3_comp246.yaml
- devices/common_patches/f3_comp246_inmsel3.yaml
- devices/common_patches/f3_comp2_inp_dac.yaml
- devices/common_patches/f3_opamp12.yaml
- devices/common_patches/f3_opamp1234.yaml
- devices/common_patches/f3_opamp2.yaml
- devices/common_patches/f3_syscfg.yaml
- devices/common_patches/f3_syscfg_cfgr1_dac2_ch1_dma_rmp.yaml
- devices/common_patches/f3_syscfg_cfgr1_i2c3_fmp.yaml
- devices/common_patches/f3_syscfg_cfgr1_mem_mode_3.yaml
- devices/common_patches/f3_syscfg_cfgr2.yaml
- devices/common_patches/f3_syscfg_cfgr4.yaml
- devices/common_patches/f3_syscfg_rcr_page8-15.yaml
- devices/stm32f301.yaml
- devices/stm32f302.yaml
- devices/stm32f303.yaml
- devices/stm32f373.yaml
- devices/stm32f3x4.yaml
- devices/stm32f3x8.yaml
split stm32f3 syscfg_comp_opamp into 3 separate devices, syscfg, comp and opamp to match the datasheet and fix all registers that need to be fixed.
> F3 syscfg / comp / opamp

- devices/common_patches/f0_ram_parity_check.yaml
- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- peripherals/flash/flash_f0.yaml
- peripherals/flash/flash_f04x_f09x.yaml
This adds full coverage of the Flash peripheral for all stm32f0 devices. Wasn't too sure what to document for `nBOOT0` and `nBOOT1`; they could probably be improved. Functionally I'm fairly confident it's all good to go, however.
Let me know if anything needs fixing.
> Flash peripheral support for stm32f0xx

- README.md
- devices/stm32f100.yaml
- devices/stm32f101.yaml
- devices/stm32f102.yaml
- devices/stm32f103.yaml
- devices/stm32f107.yaml
- devices/stm32f215.yaml
- devices/stm32f217.yaml
- devices/stm32f301.yaml
- devices/stm32f401.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f410.yaml
- devices/stm32f411.yaml
- devices/stm32f412.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
- devices/stm32f7x2.yaml
- devices/stm32f7x3.yaml
- peripherals/usart/_v2_ABC_common.yaml
- peripherals/usart/uart_common.yaml
- peripherals/usart/uart_sample.yaml
- scripts/svdpatch.py
This also add support for a new `_derive` instruction to mark an existing peripheral as derivedFrom another one, and allows to set a derivedFrom for peripheral `_add`.
> Uart fixes and documentation on F1, F2 and F7

- devices/stm32h7x3.yaml
* Maybe the prefix stripping could be automated in `svdpatch`. It would also apply to a bunch of other peripherals in that stm32h7 SVD.
* ~~DMAMUX1/DMAMUX2 are handled individually and not by pattern match because the README states that renames must not use pattern matches.~~ Pattern renames seem to work just fine in this case.
* The DMA1 interrupts are in fact listed the SVD, but under wrong names (e.g. `DMA_STR0`) ~~and they don't appear in the crate output~~. AFAICT `svdpatch` does not support renaming interrupts (#163 #170) and therefore they are just added with the correct names/description/values and override the wrong ones.
> stm32h7 dma and dmamux fixes

- devices/stm32h7x3.yaml
- peripherals/spi/spi_v3.yaml
Two things are not covered:
The SVD has all six SPI peripherals the same and derived from SPI1.
In reality only SPI123 are as documented. SPI456 have 16 bit wide TX and
RX registers and DSIZE is limited accordingly.
Furthermore, there should be explicit byte and half-word access to the
TX and RX data registers. This is how the access-transfer packing ratio
is determined.
> stm32h7x3: add SPI peripheral documentation

- devices/stm32h7x3.yaml
Some have not been touched:
* HRTIM*: needs some serious fixing and renaming with derived peripherals
* the ethernetl peripherals (DMA, MMC, MTL, MAC): there should probably
be some stripping but since there is already documentation
for the fields, the impact would be bigger
* OPAMP*, DFSDM: would leave some registers starting with a number
> stm32h7x3: _strip prefixes

- devices/stm32h7x3.yaml
- peripherals/spi/spi_v3.yaml
* The RM has FTHLV for "Fifo THreshold LeVel"
* This adopts the RM spelling
* This is presumably a breaking change as it renames a field.
> stm32h7x3: fix CFG1.FTH{V<->L} spelling

- devices/common_patches/h7_ethernet_desc.yaml
They were lost in the new SVD update process.
Found with the MMAPs from `svdmmap.py`.
> stm32h7: improve/fix two descriptions

- devices/common_patches/dma/dma_v2.yaml
Fixes #213 
@burrbull I think you added this `dma_v2.yaml` the first time, was this just a mistake or is there a reason to not have PAR?
> Add PAR to dmav2 cluster

- devices/stm32h7x3.yaml
These two bits may be written by software, although they may also be
cleared by hardware. The RM says "TXPIE is set by software and cleared
by TXTF flag set event."
The bitfield in the RM describes these bits as `rs`, rather than
`rw`. Perhaps why they are mis-classified as read-only in the SVD.
> stm32h7x3: spi `DXPIE`/`TXPIE` enables are in fact read-write

- devices/stm32h7x3.yaml
Fix some subtle errors
* stm32h7: fix write-only and read-only registers in FLASH
* stm32h7: Fix confusion between USART and UART in RCC RSTR / ENR
> stm32h7x3: flash access and usart/uart confusion

- devices/stm32l4x3.yaml
It appears #141 missed the crrcr register for the L4x3 chips, this PR addresses that.
> Add missing crrcr reg for l4x3 series chips

- peripherals/rcc/rcc_v3.yaml
- peripherals/rcc/rcc_v3_h7_ccip.yaml
* Also rename `MCO` clock selection to show which all output is selected. A breaking change!
> stm32h7x3: RCC additional definitions

- devices/common_patches/otg_hs_fixes.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
This PR should fix some of the biggest issues in OTG HS definitions (especially missing registers).
It might be a bit tricky to review the changes, as the missing registers are not directly mentioned in the documentation due to errors in the documentation itself.
> OTG HS peripheral fixes

- devices/common_patches/h7_adc_boost_rev_v.yaml
- devices/stm32h743v.yaml
- devices/stm32h753v.yaml
Documented in RM0433 Section 24.6.3
> stm32h7: Rename stm32h7x3: ADC CR boost field is wider for rev v

- devices/common_patches/l0_nvic_prio_bits.yaml
- devices/stm32l0x1.yaml
- devices/stm32l0x2.yaml
- devices/stm32l0x3.yaml
I was using the stm32l0 crate with RTFM and noticed some funky behavior. The number of NVIC priority bits are two on the m0/m0+, and it was wrong in the SVD file.
> Set correct number of nvic priority bits available on stm32l0xx

- Makefile
This prevents Make from deleting the SVD files it considers as intermediate, and then re-creating them using the extraction script.
> Mark extracted SVDs as precious to prevent auto deletion by Make

- scripts/group.py
- scripts/makecrates.py
- scripts/makedeps.py
- scripts/matchperipherals.py
- scripts/svdpatch.py
By default Python uses default system encoding for opening files, which might cause parsing errors, because all the YAML files are UTF-8 (at least to my knowledge).
> Use UTF-8 for opening YAML files

- svd/extract.sh
This should fix unzipping on platforms where asterisk doesn't match path separators.
> Fix SVD unzip matching

- devices/common_patches/h7_common_singlecore.yaml
Now agrees with RM0433.
Patch for dual core already in PR #276.
> stm32h7: correct PLL2DIVR field names

- scripts/makecrates.py
It was missing build.rs and README.md in the list of files it
autogenerate.
> Update documentation of the makecrates.py script

- devices/stm32f3x4.yaml
Three changes for the stm32f334:
- Seven interrupt numbers for HRTIM are adjusted according the manual. 
- "HRTIM1" is changed to "HRTIM" in 5 of 7 interrupt names.
- Double definition of the interrupts "CAN_SCE" and "FPU" are squashed.
Although it didn't seem to bother the build system.
> HRTIM interrupt numbers for f334

- devices/common_patches/g4_rcc.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
These renamings bring the SVDs into alignment with RM0440.
> RCC naming fixups for STM32G4 devices

- devices/common_patches/h7_ethernet_combined_desc.yaml
- devices/common_patches/h7_ethernet_desc_combined.yaml
- devices/common_patches/h7_ethernet_dma.yaml
- devices/common_patches/h7_ethernet_mtl.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h757cm7.yaml
Split ethernet peripheral into (MAC, DMA, MTL).
This brings it in line with single core parts.
> stm32h7: split ethernet peripheral for dualcore parts

- devices/stm32l0x1.yaml
The bit offset for enabling the clock for TIM3 in RCC is incorrect for stm32l0x1 targets. It should be bit 1 instead of bit 2. 
Tested on an stm32l051.
> Correct bit offset for enabling TIM3 in RCC/APB1ENR

- devices/common_patches/l0_syscfg_cfgr.yaml
- devices/stm32l0x1.yaml
- devices/stm32l0x2.yaml
- devices/stm32l0x3.yaml
I have compared the result against all 3 reference manuals and it looks
correct.
`ENREF_HSI48` was accidentally removed in #293, but it's only absent from the l0x1, not the others.
> Fix SYSCFG CFGR3 register fields

- README.md
- devices/stm32f301.yaml
- devices/stm32f3x8.yaml
- scripts/svdpatch.py
Some svd files are missing entirely a peripheral or contains a totally wrong description of a peripheral, while the correct peripheral already exists in another svd file.
This PR allows copying a peripheral from one svd file to another.
This new feature is applied to fix stm32f301 TIM1 and stm32f3x8 ADC1.
> improve copy_peripheral() to support copying from another svd file

- devices/stm32f412.yaml
The STM32F412 SVD is missing the registers RCC_AHB3RSTR and RCC_AHB3ENR. This commit adds them.
> STM32F412: Add missing reset and enable registers for AHB3

- devices/common_patches/l0_flash.yaml
I need some help getting this over the finish line. When I try to build the crates according to the instructions in README, I get this when executing `make svd2rust`:
```
python3 scripts/makedeps.py devices/stm32l0x1.yaml > .deps/stm32l0x1.d
python3 scripts/makedeps.py devices/stm32l0x3.yaml > .deps/stm32l0x3.d
python3 scripts/makedeps.py devices/stm32l0x2.yaml > .deps/stm32l0x2.d
python3 scripts/svdpatch.py devices/stm32l0x3.yaml
python3 scripts/svdpatch.py devices/stm32l0x1.yaml
python3 scripts/svdpatch.py devices/stm32l0x2.yaml
Traceback (most recent call last):
File "scripts/svdpatch.py", line 893, in <module>
main()
File "scripts/svdpatch.py", line 889, in main
svd.write(svdpath_out)
File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 772, in write
serialize(write, self._root, …
```
> Fix access of FLASH_SR.EOP in STM32L0

- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
This is a fix of the number of NVIC prio bits in the F0 line of MCUs.
This breaks RTFM (related issue: https://github.com/rtfm-rs/cortex-m-rtfm/issues/287), but this PR should fix it.
Closes https://github.com/stm32-rs/stm32-rs/issues/324
> Fixed F0 line number of NVIC prio bits

- devices/common_patches/h7_exti_singlecore.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
> stm32h7: fix EXTI access for single core parts

- devices/stm32l4x1.yaml
See [the reference manual](https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/b0/ac/3e/8f/6d/21/47/af/DM00151940/files/DM00151940.pdf/jcr:content/translations/en.DM00151940.pdf) on page 221, bit 14. In the SVD this is mislabeled as SPI1EN.
> stm32l4x1: Fix incorrect label APB1ENR1 bit 14 as SPI1EN to SPI2EN

- devices/stm32f745.yaml
- devices/stm32f765.yaml
- devices/stm32f7x2.yaml
- devices/stm32f7x3.yaml
- devices/stm32f7x6.yaml
- devices/stm32f7x7.yaml
- devices/stm32f7x9.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h757cm7.yaml
All those SVDs already have their nvicPrioBits set to 4 so there is no
need to patch them.
> Cleanup needless nvicPrioBits patching

- devices/common_patches/f3_comp1234567.yaml
- devices/common_patches/f3_comp246.yaml
- devices/stm32f303.yaml
- devices/stm32f373.yaml
- devices/stm32f3x8.yaml
To-do: check other devices using `common_patches/f3_comp246` to see if they also require these interrupts.
> Add COMP2 and COMP4_6 interrupts for STM32F3x4

- devices/common_patches/g4_comp.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
Thanks for all your work on this project, it's really cool to be able to write Rust on microcontrollers!
In my YAML patch I quoted the offsets so they're written out as hex in the generated SVD to match section 23.6.2 in STM reference manual RM440:
I've verified that the patch works to correct COMP6 on an stm32g474 nucleo board.
> Correct stm32g4 comparator register offsets.

- devices/common_patches/h7_dmamux.yaml
@richardeoin, would you mind having a very quick look at this? #317 noticed that SOF is not split, and we already split a bunch of similar fields, so it seems OK.
> Split SOF in DMAMUX.CSR. Closes #317.

- devices/common_patches/dma/dma_v21.yaml
- devices/stm32f413.yaml
- devices/stm32f765.yaml
- devices/stm32f7x2.yaml
- devices/stm32f7x3.yaml
- devices/stm32f7x7.yaml
- devices/stm32f7x9.yaml
- peripherals/dma/dma_v21.yaml
Some F4 and F7 have a 3 bits CHSEL and others have a 4 bits CHSEL.
This provides separate patches for the different bitWidth.
> Fix DMA CR CHSEL bitWidth

- devices/stm32f401.yaml
I have added the missing interrupt handlers in the same manner as already done for USART2/6
> Stm32f401: add TIM[4, 5] + DMAx_STREAMy Interrupts

- stm32_part_table.yaml
- stm32f4/README.md
Should I also update links in the [README](https://github.com/stm32-rs/stm32-rs/blob/master/stm32f4/README.md) or they are automatically generated in some way?
> fix stm32f4 links to st website

- devices/common_patches/h7_sai.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
SAI peripheral applies to the H7 also. Note that we introduce the very slightest difference with RM0433 (single core 743/753) by setting `[AB]CR1.NOMCK` -> `[AB]CR1.NODIV`. Whilst RM0433 uses `NOMCK`, both RM0399 (later dual core parts) and `sai/sai.py` use `NODIV`.
The description in `sai/sai.py` has text from both the old and new definitions, and it appears the functionality of the bit is unchanged.
[AB]FRCR.FSDEF is marked as read only in the SVD and the register diagram in the RM. However, in the prose text in RM0399 it is clearly noted as read-write "This bit is set and cleared by software."
> sai: sai_v1 patch and sai peripheral apply to H7. Fix FSDEF

- devices/stm32l4x2.yaml
This PR fixes #349 by renaming the SPI1EN bit of `RCC_APB1ENR1` to `SPI2EN` according to the datasheet. Additionally, it adds the `TIM3RST` as bit 1 of `RCC_APB1RSTR1`.
From the [datasheet](https://www.st.com/resource/en/reference_manual/dm00151940.pdf):
> Correcting STM32L4 RCC registers

- devices/stm32f412.yaml
- devices/stm32f413.yaml
Signed-off-by: Daniel Egger <daniel@eggers-club.de>
> Correct the incorrect FSMC peripheral base address on the F412/F413

- scripts/makecrates.py
This should significantly reduce resource usage on docs.rs, ref #303, #3, https://github.com/rust-lang/docs.rs/issues/608
> Update makecrates to tell docs.rs to only build for one target

- devices/common_patches/fpu_interrupt.yaml
- devices/stm32f303.yaml
- devices/stm32f3x4.yaml
- devices/stm32f401.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f410.yaml
- devices/stm32f411.yaml
- devices/stm32f412.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
- devices/stm32l4x1.yaml
- devices/stm32l4x2.yaml
As detailed in issue #352, a lot of microcontrollers svd have a duplicated FPU interrupt entry.
This problem has already been fixed for stm32f3x4.
This commit apply this fix to all the other microcontrollers that need it.
> fix fpu double interrupt

- devices/common_patches/h7_common_dualcore.yaml
- devices/common_patches/ramecc/ramecc.yaml
- devices/common_patches/ramecc/ramecc_new.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
RAMECC was 'added' to the single core parts in RM0433 Rev 7. For the dual core parts there are definitions in the SVD, but they are so terrible it's worth starting over (there are registers with the wrong address, and the wrong fields)
For a use case, there is at least one set of commercial spaceflight hardware using the H7:
(no affiliation, no endorsement intended)
- [Nanoavionics OBC](https://nanoavionics.com/cubesat-components/cubesat-on-board-computer-main-bus-unit-satbus-3c2/)
> Add RAMECC registers across the H7 family

- devices/common_patches/tim/tim14_16bit_l.yaml
- devices/common_patches/tim/tim15_16bit_l.yaml
- devices/common_patches/tim/tim16_16bit_l.yaml
- devices/common_patches/tim/tim1_16bit_l.yaml
- devices/common_patches/tim/tim_1ch_16bit_l.yaml
- devices/common_patches/tim/tim_2ch_16bit_l.yaml
- devices/stm32f0x0.yaml
- peripherals/tim/tim14_16bit.yaml
- peripherals/tim/tim15_16bit.yaml
- peripherals/tim/tim16_16bit.yaml
- peripherals/tim/tim1_16bit.yaml
- peripherals/tim/tim_1ch_16bit.yaml
- peripherals/tim/tim_2ch_16bit.yaml
TIM2 through 5 already have a patch like this, but those timers (like
TIM1) have four channels.  For the 2-channel TIM15 and the 1-channel
TIM14/16/17, create a new 2ch and 1ch generic patch, and include it from
the right per-timer patch file.
This all matches the reference manual.
(I could have tried to combine all the 1-channel timers into a single
timx_16bit.yaml file, but x becomes hard to read.  141617 doesn't make
nearly as much sense as 2345 does; 1467 makes even less sense.  So I
just put them each into their own file.)
> stm32f0x0 TIM1, 14-17 are all 16-bit; patch.

- devices/common_patches/flash/flash_dual_bank.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
The goal here is to unify the naming of the common flash registers accross all h7 parts. Sadly this solution still leaves the register fields themselves named with a trailing 1, unlike the 747cm7/4 parts where we delete the flash peripheral and start over.
> h7: Apply flash bank grouping to all parts

- devices/common_patches/h7_common_dualcore.yaml
Now matches singlecore parts as well as RM
> h7: Rename HDMICEC -> CEC in APB1Lxxx registers to match latest RM

- devices/common_patches/g4_adc.yaml
- devices/common_patches/g4_adc_common.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- peripherals/adc/adc_v3_common_f3_single.yaml
- peripherals/adc/adc_v3_common_g4.yaml
- peripherals/adc/adc_v3_common_h7.yaml
- peripherals/adc/adc_v3_common_single.yaml
- peripherals/adc/adc_v3_g4.yaml
This adds the register descriptions for each of the ADCs in the STM32G4 series.
For now it only matches ADC1 and ADC3 because 2, 4 and 5 are sometimes and sometimes not derived from 1 and 2. Though technically they are the same peripheral.
Is there any preferred way to work around this?
Register names are not exactly as in RM0440 and lack the universal "ADC_" prefix, others seemed to omit them too so I tried to match that.
> Add descriptions for STM32G4 ADC registers

- devices/stm32f412.yaml
The Flexible Static Memory Controller (FSMC) definitions had some extraneous registers, extraneous bits, missing bits, and incorrect reset values. With this change, everything should be consistent with the STM32F412 reference manual.
> STM32F412 FSMC register cleanup

- devices/common_patches/h7_common_highmemory.yaml
- devices/stm32h7b3.yaml
- stm32_part_table.yaml
- svd/extract.sh
ST doesn't appear to have a coherent name for these parts, but "high memory density" seems to be a good description. The Reference Manual is RM0455
`h7_common_highmemory.yaml` has parts from both the existing `_singlecore.yaml` and `_dualcore.yaml` (and some special parts, of course)
`../peripherals/dma/dmamux_v1.yaml` applies, but throws an error.
> Add basic support for H7B3 "high memory density" line

- devices/common_patches/h7_dbgmcu.yaml
Update to match latest version of RM0433 and RM0399. Based on discussion with @diondokter [here](https://github.com/stm32-rs/stm32h7xx-hal/issues/7) setting these bits causes some undocumented clock gating or logic problem in the DBGMCU. ST have likely removed these bits to 'solve' this problem.
> h7: Change DBGSTBY_D3 and DBGSTOP_D3 to reserved in DBGMCU CR

- peripherals/dma/dma_v1.yaml
- peripherals/dma/dma_v3.yaml
- peripherals/eth/eth_dma_common.yaml
Currently we mark these fields with a writeConstraint of any 32-bit value, which means svd2rust generates a safe `bits()` method to write to them. In turn, this allows entirely safe code to use the DMA to read or write any address, which can cause memory unsafety.
Ideally perhaps svd2rust shouldn't act like this, but by removing these writeConstraints we make the relevant `bits()` methods unsafe, so unsafe code is required to use the DMA engine. A HAL with a DMA driver can implement a safe abstraction using the upcoming DMA traits to ensure the addresses being written do not lead to unsafety.
What do people think about this change? Especially it might impact @thalesfragoso's DMA and stm32-eth work.
> Do not add writeConstraints to DMA address registers

- devices/common_patches/h7_common_dualcore.yaml
- devices/common_patches/h7_common_highmemory.yaml
- devices/common_patches/h7_common_singlecore.yaml
The effect of this PR is different between the H7 groupings:
**highmemory (RM0455):** This change brings us in line with the RM, fixing a mistake on our part
**singlecore/dualcore (RM0433/RM0399):** Breaks with the RM, instead preferring a more consistent scheme that matches RM0455. All other peripherals enable/resets are in the form name{en,rst} , so having the inconsistent name{hsen,rst} is a pain.
I'm not sure the existance of USB2ULPIEN makes any sense (the USB2 peripheral has no ULPI), but it is RM0433/RM0399.
> h7: Rename USBxOTGHSEN -> USBxOTGEN, USBxOTGULPIHSEN -> USBxULPIEN

- devices/common_patches/f3_syscfg.yaml
- devices/common_patches/f3_syscfg_cfgr1_adc2_dac1_rmp.yaml
- devices/common_patches/f3_syscfg_cfgr1_timx_dacx_chx_dma_rmp.yaml
- devices/stm32f301.yaml
- devices/stm32f302.yaml
- devices/stm32f303.yaml
- devices/stm32f373.yaml
- devices/stm32f3x4.yaml
- devices/stm32f3x8.yaml
- peripherals/syscfg/syscfg_f0.yaml
- peripherals/syscfg/syscfg_f3.yaml
- peripherals/syscfg/syscfg_f301.yaml
- peripherals/syscfg/syscfg_f302.yaml
- peripherals/syscfg/syscfg_f303_3x8.yaml
- peripherals/syscfg/syscfg_f37x.yaml
- peripherals/syscfg/syscfg_f3_cfgr2_pvd_lock.yaml
- peripherals/syscfg/syscfg_f3x4.yaml
This should cover 100 % of the syscfg register from the stm32f3 devices. 
- I left quite a view TODOs regarding naming and doubled values, as I'm unsure how to go about this
- Some files could be split to smaller chunks, to reduce the duplication (however some devices slightly differ in their description strings and syscfg control register are sometimes quiet different between the devices)
- I split up the FPU_IE into it's five flags, as it seems, that they are independent of each other (correct me if I'm wrong about this)
- This PR is split into many small commits intentionally. This should make it easier to sqaush it into larger more reasonable commits after all review comments are addressed.
> Document syscfg for stm32f3 devices

- devices/common_patches/dma/bdma.yaml
- devices/common_patches/dma/bdma_v2.yaml
- devices/common_patches/h7_common_highmemory.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
- peripherals/dma/bdma.yaml
Currently only found on the H7 I think. Applies to:
* RM0433 / RM0399: BDMA
* RM0455: BDMA1, BDMA2
Quite some bashing was required on the older SVDs to get them to match the newer RM0455. With this they do all generate the same register definitions, including an array of channels like `pub ch: [CH; 8]`
Additionally add this, dma_v3 and exti to the H747 CM4 core (not sure why they were missing?)
> Add Basic DMA

- devices/common_patches/f0_crc_init_addr_fix.yaml
- devices/stm32f0x0.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
The SVD files for the stm32f0xx devices contain the wrong address offset for the INIT register of the CRC peripheral. The SVD files specify an address offset of 0xC, while the reference manual specifies an address offset of 0x10. I verified that the correct offset is indeed 0x10, on an stm32f042.
> Fix the address of the CRC INIT register for stm32f0xx devices

- devices/common_patches/g0_dma_5ch.yaml
- devices/common_patches/g0_dma_7ch.yaml
This makes it more convenient to split up the HAL DMA driver in separate channels.
Inspired by stm32f3.
> Group DMA registers on STM32G0 series

- devices/common_patches/h7_common_highmemory.yaml
- devices/common_patches/h7_rcc_src_sel.yaml
- devices/stm32h7b3.yaml
- peripherals/rcc/rcc_v3_h7_ccip.yaml
Quick coverage of two points from https://github.com/stm32-rs/stm32h7xx-hal/pull/122
* Rename d3ccip -> srdccip (ref https://github.com/stm32-rs/stm32h7xx-hal/issues/95 ), fix field naming in that register
* Strip `SDMMC_` prefix from sdmmc registers
> stm32h7: rcc ccip patches and sdmmc prefix for b3

- scripts/makecrates.py
We are trying to implement the support for the STM32MP1 family.
The `makecrates.py` script is currently retrieving the chip name by slicing the 7 first chars from the full chip name.
This pull request propose to match the chip name with a regex instead.
> Add support for family with more than one letter

- peripherals/crc/crc_advanced.yaml
The advanced CRC peripheral, present on e.g. the stm32f0 series, can process input data by byte, half-word or word. Currently, the CRC's DR register is only defined as a word-sized register, making it impossible to supply input data by half-word or byte.
This patch adds two "virtual" DR8 and DR16 registers to the advanced CRC peripheral. They are both mapped to the same base address as the DR register, but come with a width of 8 and 16 bits respectively. These virtual registers allow writing data per byte or half-word to the DR register.
From RM0091:
> Add virtual DR8 and DR16 registers to the advanced CRC peripheral

- peripherals/adc/adc_v3_g4.yaml
- peripherals/rcc/rcc_common.yaml
As reported in https://github.com/stm32-rs/svdtools/pull/31, some patches here produce multiple overlapping `<enumeratedValues>` tags in the patched SVD file.  This can be fixed by ensuring the two patch statements in question don't overlap.
I'll leave this PR a draft until all discussions in the above mentioned PR to `svdtools` are resolved, in case anything else comes up.
> Fix duplicate enums

- Makefile
- scripts/makecrates.py
When running `make`, the `makecrates.py` scripts will retrieve every yaml files and run on every single one of them.
When making changes on a single family (or not all of them at least), one can edit the `CRATES` variable in `MakeFile` to specify the families that needs to be generated.
When running the script manually without specifying this new parameter, the behaviour will stay the same.
> Add optional `families` parameter to makecrates.py

- scripts/makecrates.py
#424 is breaking the build system:
usage: makecrates.py [-h] [-y] [--families FAMILIES] devices
makecrates.py: error: unrecognized arguments: stm32f1 stm32f2 stm32f3 stm32f4 stm32f7 stm32h7 stm32l0 stm32l1 stm32l4 stm32l5 stm32g0 stm32g4
This fix uses space to separate arguments instead of comma.
> [scripts/makecrates] Use space instead of comma, fixes `make crates`

- devices/stm32f412.yaml
There are several interrupts defined in reference manual RM0402 that are missing from the SVD. This change adds them.
> STM32F412: Add missing interrupts

- peripherals/tim/tim21.yaml
I have found some missing field options for `TIM2x`. This patch is probably not the best approach and I will be happy to fix it if anyone can please point me to the right direction why the `tim_ccm_v1.yaml` doesn't work for `TIM2x`.
> TIM21: Fix ccm missing options

- devices/common_patches/dma_interrupt_names.yaml
- devices/stm32l4x3.yaml
- devices/stm32l4x5.yaml
- devices/stm32l552.yaml
- devices/stm32l562.yaml
This PR requires https://github.com/stm32-rs/svdtools/pull/34 be released before it can be merged.
> Rename DMA interrupts for STM32L4x3, L4x5, L552, L562. Closes #430.

- devices/common_patches/h7_common_highmemory.yaml
Ended up changing some peripherals too:
* DAC -> DAC1
* Add DAC2
* USART9 -> UART9
> stm32h7: add or fix interrupts for b3

- devices/common_patches/h7_crc_addr_fix.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
According to RM0433, RM0399, and RM0455 `INIT` is at 0x10 and `POL` is at 0x14. (See for example [page 798/section 21.4.4 of RM0433](https://www.st.com/resource/en/reference_manual/dm00314099-stm32h742-stm32h743-753-and-stm32h750-value-line-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=798).) SVDs have them both four bytes earlier.
Tested on an STM32H750VBT6.
> Fix H7 CRC INIT and POL register addresses

- devices/stm32f750.yaml
- stm32_part_table.yaml
This addresses #226.
I tested this on a STM32F7508-DK Discovery kit, and I can say that at least the most important peripherals work. 
The peripherals were matched automatically using `matchperipherals.py`; the `patch` process succeeds, but the majority remain untested on the device itself.
> Add STM32F750 device

- devices/stm32l4x1.yaml
- devices/stm32l4x2.yaml
- devices/stm32l4x3.yaml
Hi, I renamed the ADC to ADC1 to follow the datasheet.
It was not needed for the rest of the series, they had the correct name.
One question, ADC2 is missing and it shouly be on L412 and L422, but the feature flags do not have this granularity.
How should I add this?
Table for overview:
> ADC -> ADC1 fix for STM32L4xx series

- devices/stm32l552.yaml
The timer documentation also seems 'broken'.  Table from RM0438 below.  I'm assuming acronym column is incorrect in the doc, so fixing that as well as adding missing interrupts from TIM6 & TIM7.
> Fix STM32L552 TIMx interrupts

- devices/common_patches/f3_gpio_ospeedr.yaml
- devices/stm32f301.yaml
- devices/stm32f302.yaml
- devices/stm32f303.yaml
- devices/stm32f373.yaml
- devices/stm32f3x4.yaml
- devices/stm32f3x8.yaml
F3 mcus does not support very high speed mode in OSPEEDR register.
This patch ignores the `0b10`.
> Fix GPIO OSPEEDR variant on f3

- devices/stm32l552.yaml
- devices/stm32l562.yaml
- peripherals/gpio/gpio_l5.yaml
This change replicates the approach taken for the L0 family.  Note: in L0 and L5 families, the documentation has the Alternate Function selection documented as 'AFSEL', rather than 'AFR', so generic gpio_v2 patch does not apply.
> STM32L5: add GPIO enum values

- devices/common_patches/g4_rcc.yaml
Closes #480.
Modifies SP3EN to SPI3EN for APB1ENR1 register for the G4 Family.
> Rename SP3EN to SPI3EN for G4 Family

- peripherals/rcc/rcc_common.yaml
RM0008 says this is correct, see "7.3.2 Clock configuration register (RCC_CFGR)".
> Fix RCC SWS doc typo

- devices/common_patches/l4_adc_smpr.yaml
- devices/stm32l4x1.yaml
- devices/stm32l4x2.yaml
- devices/stm32l4x3.yaml
- devices/stm32l4x5.yaml
Fixed SMP fields docs in L4 series, and missing SMP0 field
> Fix for missing SMPR field

- devices/common_patches/g4_swap_IWDG_WWDG.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- peripherals/wwdg/g4_wwdg.yaml
Closes #474.
Adds a patch, `devices/common_patches/g4_swap_IWDG_WWDG.yaml`, that restores the correct values for the IWDG and WWDG peripherals for the g4 family of devices.
Adds this newly added patch to the whole g4 family configuration files.
Further adds the IWDG peripheral configuration file to the whole g4 family.
> Correct IWDG and WWDG peripherals for the g4 family

- devices/common_patches/fdcan/fdcan_common.yaml
- devices/common_patches/fdcan/fdcan_g4.yaml
- devices/common_patches/fdcan/fdcan_h7.yaml
- devices/common_patches/h7_common_dualcore.yaml
- devices/common_patches/h7_common_highmemory.yaml
- devices/common_patches/h7_common_singlecore.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
FDCAN appears in the H7, G4, L5 and MP1 families. The peripheral varies between the families, with the G4/L5 versions being somewhat simpler. I don't see any variation within families, but haven't exhaustively checked for this.
On the H7, the FDCAN2 doesn't support TTCAN. However FDCAN2 is `derivedFrom="FDCAN1"` in the original ST SVDs (and remains so). The RM isn't very clear about which registers are missing from FDCAN2, but we could to remove the `TT*` registers from FDCAN2 if this is important.
G4 devices have either 1 or 3 FDCANs.
Checked against:
H7 RM0399
G4 RM0440
> Add basic patches for FDCAN

- devices/common_patches/g4_cordic.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- peripherals/cordic/cordic_g4.yaml
Add CORDIC math accellerator enum definitions to stm32g4 family    
- modified description on mislabeled registiers
- added clarifying descriptions for two CORDICs CSR fields
> Add CORDIC math function accelerator support to stm32g4

- devices/stm32l4x5.yaml
I noticed when extending the STM32L4xx HAL that this MCU had some bits with different names compared to the rest of the series.
This PR fixes this.
> Fixed ch17 and ch18 in ADC COMMON for STM32L4x5

- devices/common_patches/f3_exti_offset.yaml
- devices/stm32f301.yaml
- devices/stm32f302.yaml
- devices/stm32f303.yaml
- devices/stm32f3x4.yaml
Fix for f3 EXTI peripheral
* Address offset is wrong for `*2` registers
* f301 should have `*1` and `*2` registers
* The same problem exists on f3x8, will be fixed by #495
> F3 EXTI fix

- devices/stm32f469.yaml
This PR closes #487. F469/79 is the only device affected in the F4 family.
> Add DSI host global interrupt for STM32F469

- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- devices/stm32g491.yaml
- devices/stm32g4a1.yaml
- peripherals/opamp/opamp_g4_common.yaml
- peripherals/opamp/opamp_g4_opamp4_5.yaml
- peripherals/opamp/opamp_g4_opamp6.yaml
Verified with RM0440 the OpAmp register count for each chip in the family.
+ stm32g491 was missing OPAMP6
| Feature | STM32G474/STM32G484 | STM32G473/STM32G483 | STM32G471 | STM32G431/STM32G441 | STM32G491/STM32G4A1 |
|---|---|---|---|---|---|
| OPAMP | 6 (OPAMP1..6) | 6 (OPAMP1..6) | 4 (OPAMP1.2,3,6) | 3 (OPAMP1..3) | 4 (OPAMP1.2,3,6) |
Note that actually in STM32Cube header files stm32g471 doesn't have 4th Opamp, so leaving it off from this change - until actual hardware can be checked
> Add OPAMP enums for STM32G4

- CHANGELOG.md
- Makefile
- README.md
- scripts/makecrates.py
I plan to release 0.13.0 very soon, once a few more outstanding PRs have been merged. Just preparing the changelog in advance here.
I sort of expect 0.14.0 will use a new svd2rust build which may have some breaking changes, hopefully can get that released quicker than 0.12 to 0.13!
> Prepare for v0.13.0 release

- devices/common_patches/h7_wwdg.yaml
- devices/common_patches/h7_wwdg1.yaml
- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- devices/stm32g491.yaml
- devices/stm32g4a1.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
- peripherals/wwdg/wwdg_v2.yaml
Fixes #501 
- Renamed the G4 wwdg to wwdg_v2
- Created patch for the bit width
- Added the patch to the H7 devices (I checked the datasheets and they all have the bigger prescaler)
> WWDG prescaler fix for H7

- .github/workflows/nightlies.yaml
Seems to have been left out of #467, this adds the stm32wb crate to the nightlies repo.
> Add stm32wb to nightly releases

- devices/stm32h747cm7.yaml
Not sure why they were missing
> h7: LTDC field definitions apply for stm32h747cm7 too

- devices/stm32l552.yaml
- devices/stm32l562.yaml
This PR closes #511. TIM15 on L552 and L562 are the only timers affected by this issue.
> Fix TIM15 CCR2 address offset for STM32L5xx

- devices/common_patches/l4_adc_sqr1.yaml
- devices/stm32l4x1.yaml
- devices/stm32l4x2.yaml
- devices/stm32l4x3.yaml
- devices/stm32l4x5.yaml
- devices/stm32wb55.yaml
This PR closes #513. In addition to L4x1, L4x2, L4x3, and L4x5, this issue also affected WB55.
> Fix ADC SQR1.L name and description for L4xx and WB55

- devices/stm32l4x3.yaml
This PR closes #525. L4x3 is the only device in the L4 family affected by this issue.
> Add missing APB1RSTR1.USBFSRST field for L4x3

- devices/stm32l4x3.yaml
Discovered when attempting to enable CRC hardware module.
```rust
let crc_guy = dp.CRC.constrain(&mut rcc.ahb1);
```
CRC output would be 0. Found with debugger that the enable bit was not
being set in rcc.ahb1 power enable register. Other peripherals in the
register (DMA1/2) could be enabled and the remaining bits in the
register are not writable.
Tested against the following code provided by STM32CubeMX, in which the
CRC module is functional.
- CMSIS/Device/ST/STM32L4xx/Include/stm32l433xx.h
- STM32L43xxx... Reference Manual RM0394 Rev 4. Sections 6.4.9, 6.4.15, 6.4.21
- Bug Verified/Fixed/Tested on STM32L433 (Nucleo-L433RC-P)
> Fix bit shift in AHB1 register for CRC enable/reset/sleep-mode bits, STM32L4x3.svd patch 

- devices/stm32g431.yaml
- devices/stm32g441.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- devices/stm32g491.yaml
- devices/stm32g4a1.yaml
I think the register definitions in gpio_v2.yaml match those of the stm32g4 series so I added them to the device files.
> Added peripherals/gpio/gpio_v2.yaml to stm32g4 series

- devices/stm32f446.yaml
So I almost made the same mistake as #374, but actually managed to notice that before starting a pull request, so here I just included the [flash_v1.yaml](https://github.com/stm32-rs/stm32-rs/blob/master/peripherals/flash/flash_v1.yaml) to the f446 device file.
(Apparently, the decision was made not to fiddle with `_read/_write` for 'write 1 to reset' in the library, so I abstained from including that for the FLASH.SR bits)
Moreover, SVD apparently missed PLLR field for some reason, so I based that fix on the similar solution from the f412 patch.
> STM32F446: FLASH description, RCC.PLLCFGR.PLLR

- devices/common_patches/l4_spi.yaml
- devices/stm32l4x1.yaml
- devices/stm32l4x2.yaml
- devices/stm32l4x3.yaml
- devices/stm32l4x5.yaml
- devices/stm32l4x6.yaml
- peripherals/spi/spi_l4.yaml
RM0394 documents the L4 series.
The common SPI mostly applies, but L4 series SPI differs from SPI_v1, v2 and v3 variants - so defining an 'spi_l4' variant.
Two SVD fields need renaming as part of this to be consistent with documented field names (and the ST-provided C HAL):
- CR1.CRCL
- SR.FRE
> SPI for L4 series

- devices/common_patches/i2c_v1_fltr.yaml
- devices/stm32f401.yaml
- devices/stm32f410.yaml
- devices/stm32f411.yaml
- devices/stm32f412.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
- peripherals/i2c/i2c_v1_fltr.yaml
This adds the I2C FLTR register defined in RM0368. I have tested this result in code that compiles and looks correct to me (see below). However, I have not tested that this indeed does the right thing in hardware. Not even sure how I would do that :).
```rust
i2c1.fltr.write(|w| w.anfoff().enabled().dnf().no_filter());
```
I only made changes in `devices/stm32f401.yaml` as I personally don't know whether other similar devices have this. For example, STM32L4 does not follow this structure, but maybe other STM32F4's do? Don't know.
> STM32F401: Add FLTR register to all I2C peripherals

- devices/common_patches/f0_adc_fixes.yaml
- devices/common_patches/f0_dmaen.yaml
While consuming a patched F0 SVD from https://github.com/lynaghk/svd2zig/ I noticed that a few patches add registers which alias existing ones at the same `bitOffset`.
E.g., [AUTDLY](https://github.com/stm32-rs/stm32-rs-nightlies/blob/7f67ec12360dfdfa9ce08aa76bf088c17f21cdc9/stm32f0/src/stm32f0x0/adc/cfgr1.rs#L1180-L1184) and [WAIT](https://github.com/stm32-rs/stm32-rs-nightlies/blob/7f67ec12360dfdfa9ce08aa76bf088c17f21cdc9/stm32f0/src/stm32f0x0/adc/cfgr1.rs#L1230-L1234).
Based on the ST reference doc:
I suspect the patch intent was actually to replace the former with the latter.
Ditto with DMA, which should also (I suspect) modify rather than alias:
> F0 patches that rename registers should modify the existing register

- README.md
Issue #547 mentions this but it would be nice to have this information in this prominent place. Version 0.17.0 works for me.
> Mention actually required version of svd2rust

- peripherals/usart/_v2_ABC_common.yaml
The STM32F303 has 9 bit wide RDR and TDR registers and according to the SVDs this is the case for all other devices with this peripheral too. Make accessing TDR via tdr().bits() safe again by providing the appropriate constraints.
I stumbled upon this issue in https://github.com/rust-embedded/discovery/pull/267#issuecomment-822826949.
The currently exisiting bitWidths have been quick-and-dirty checked using:
```bash
svd $ xmllint --xpath ".//field[(name = 'RDR' or name = 'TDR') and bitWidth != 9]" --format *.svd *.svd.patched
```
This gave not output while searching for `bitWidth = 9` did.
> Fix write constraints for USART RDR and TDR registers

- CHANGELOG.md
- README.md
- peripherals/usart/_v2_ABC_common.yaml
- scripts/makecrates.py
Contains backported #558 to allow use in Discovery book.
> Prepare for patch release of stm32f3 0.13.1

- devices/common_patches/l0_tim.yaml
The existing patch for l0 timers was setting these registers to 16-bit as a side-effect of redefining TIM2/TIM3 - but for all TIM objects, the corresponding reference manuals indicate CNT, ARR and CCRx values should be 16-bit registers.
Relevant ref manuals: RM0367, RM0376, RM0377
> l0: fix CNT, ARR, CCRx register sizes

- devices/stm32l0x2.yaml
- devices/stm32l0x3.yaml
According to the reference manuals for STM32L0x{2, 3}, the RCC_CSR
register RMVF has the offset 23 and not 24. Offset 24 is occupied by a
Firewall reset which is also added in this change
Page 219 in the STM32L0x2 release manual can be used to verify.
> Fix bit offset for RMVF in STM32l0x2 and STM32l0x3

- CHANGELOG.md
- scripts/makecrates.py
Requiring the `rt` feature seems to only catch people out, and as far as I can tell it's very rare to not want it. It's still possible to disable it if you don't want it, just now it will usually be enabled for you.
> Enable the `rt` feature by default

- devices/common_patches/fdcan/fdcan_h7.yaml
To make sure the Writable trait is also implemented for the TEST register
> Make FDCAN_TEST register writeable for H7 family

- devices/stm32f7x2.yaml
In #540 TIM5 was updated to be rebased from TIM2, but as its option register OR is different, it can't be rebased.
@burrbull I thought I'd need to instead copy it from TIM2 and then change OR, like
```yaml
_copy:
TIM5:
from: TIM2
TIM5:
_modify:
OR:
description: TIM5 option register 1
OR:
_delete:
- ITR1_RMP
_add:
TI4_RMP:
description: Timer Input 4 remap
bitOffset: 6
bitWidth: 2
```
but it looks like the plain SVD is already correct and we just don't need to do anything, can you remember why you rebased it originally?
> Revert rebasing TIM5 for F7x2, since OR must be different.

- devices/stm32f413.yaml
- peripherals/rcc/rcc_v2.yaml
Make bit names consistent with peripheral names:
USART1-3, USART6
UART4-5, UART7-10
> Fix U(S)ART RCC enable/reset bits for F4 devices

- devices/stm32wle5.yaml
The dual-core STM32WL5x variant use the `CxIMRy` naming convention on the EXTI IMR registers whereas the single-core STM32WLE5 variant uses `IMRy`.
This PR adds the `Cx` prefix to the single-core variant to reduce the occurrences of `#[cfg(feature = "stm32wle5")]`.  This matches what has already been done for other peripherals (HSEM).
cc @jorgeig-space
> stm32wle5: normalize EXTI.IMRx to match dual-core variants

- devices/stm32f3x4.yaml
Fixes an issue caused by svdtools 0.1.16.
> Set STM32F3x4 HRTIM ISR FLT* fields read-write

- scripts/makehtml.py
- scripts/makehtml.template.html
This pull request fix two bugs in the `makehtml.py` script:
- When parsing the addressOffset value, the value is parsed as base16 even if it's in base10.
- When two registers have the same addressOffset, one of the two is suppressed
The first bug is fixed by checking if the addressOffset starts with `0x` to parse from base16, or parse from base10 by default (when a register is generated from a patch).
The second bug is fixed by changing the index used for the list of registers from the addressOffset to the register name.
> [scripts/makehtml] Fix displaying of registers with the same addressOffset and parsing of addressOffset

- devices/stm32h735.yaml
- devices/stm32h743.yaml
After 0cb0f60346d21320bbfde60b37d2d14aa49439d2 the peripheral patches for the OCxM fields were no longer applied for these parts. This PR fixes that.
* Add `peripherals/tim/v2/ccm.yaml` that appeared during the refactor but wasn't added to this device
* Remove duplicate include of `common_patches/tim/tim_ccr.yaml`
> Resolve small breakage in OCxM fields for stm32h735 in #546

- scripts/makehtml.template.html
This pull request adds a "Show register map" button for each peripheral in the HTML peripheral coverage for getting a quick overview of all the fields.
> [scripts/makehtml] Add register map

- Makefile
This pull request allow to build HTML doc only for selected crates, thus reducing build time when working on specific crates.
Exemple of usage:
CRATES=stm32f7 make -j16 html
> Generate HTML doc only for selected CRATES

- scripts/makecrates.py
I am not exactly sure what this link was supposed to point to; previous it generated https://github.com/stm32-rs/stm32-rs/tree/master/stm32wl for the STM32WL which is invalid.
Now it generates a link to https://crates.io/crates/stm32wl which is valid.
> Fix dead link in generated README

- scripts/comparesvd.py
- scripts/htmlcomparesvd.py
- scripts/makehtml.py
- scripts/makejson.py
- scripts/periphtemplate.py
When comparing some peripherals I saw that some `baseAddress` where parsed as base 10 but still prefixed with "0x".
I fixed every int parsing left in the `scripts` folder to automatically use the right base.
> [scripts] Fix int base when parsing

- scripts/htmlcomparesvdall.sh
When comparing peripherals and fields from the F7 family, there is 3 big groups of MCU that we can distinguish:
- RM0431: F7x2, F7x3, F30x
- RM0385: F745, F750, F7x6
- RM0410: F765, F7x7, F7x9
This PR reorder the chips in the table so it's easier to detect a missing field or register in each group.
> [html-compare] f7: Change order of MCUs in the table

- devices/common_patches/wb_adc_common.yaml
- devices/stm32wb55.yaml
As is commonly done, use "ADC1" even when there's only one ADC.  This
makes it not only more self consistent, (interrupt names were for ADC1)
but also more consistent with sibling targets like STM32L4.
Also, like the L4, the WB svd is missing the ADC_Common registers.  Add
them back in, but note that there's less bits in the common registers.
Signed-off-by: Karl Palsson <karlp@etactica.com>
> stm32wb: ADC -> ADC1 and add ADC_COMMON

- devices/stm32wb55.yaml
Fixes: https://github.com/stm32-rs/stm32-rs/pull/473
Fixes the base address, and then for the registers after the split,
fixup their addresses manually.
Signed-off-by: Karl Palsson <karlp@etactica.com>
Is there really any need to specifically mark the VREFBUF as "reserved" within the syscfg block as discussed in #473? is that important? the memory map generated looks correct.
> stm32wb: syscfg: fix split sections

- devices/stm32wl5x_cm0p.yaml
- devices/stm32wl5x_cm4.yaml
- peripherals/flash/flash_wl.yaml
- peripherals/flash/flash_wl_c2.yaml
- peripherals/ipcc/ipcc_wl.yaml
- peripherals/pwr/pwr_wl.yaml
- peripherals/pwr/pwr_wl_c2.yaml
- peripherals/rcc/rcc_wl_c2.yaml
This adds register descriptions for registers that are exclusive to the dual-core STM32WL's
cc @jorgeig-space
> stm32wl: add register descriptions for dual-core variants

- devices/common_patches/h7_sai.yaml
- devices/common_patches/h7_sai_mcken.yaml
- devices/stm32h735.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h7b3.yaml
- peripherals/sai/sai.yaml
Other H7 parts are unchanged. Improve description of NOMCK/NODIV bit
See previous PR #347. Fixes #618
> H7 RM0433: Add NOMCK at SAI [AB]CR1 bit 19 and remove MCKEN

- devices/stm32wl5x_cm0p.yaml
- devices/stm32wl5x_cm4.yaml
- devices/stm32wle5.yaml
Other STM32 have timers in the TIM group.  For these devices, there was a mix of group names for different timer types, with a typo in one of the names 'AdavanceTimers'
This PR puts all timers in the TIM group for consistency with other STM32.
> wl5x / wle5: put all timers in TIM group

- devices/common_patches/h7_ethernet_mac.yaml
- devices/stm32h735.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
This PR fixes #656 by making the MMC_TX/RX_INTERRUPT_MASK register completely writable.
TODO:
> Updating STM32H7 ETH_MAC MMC mask register writable

- devices/common_patches/h7_common_highmemory.yaml
Previous modification did not work as this peripheral is `derivedFrom` OCTOSPI in the original SVD
> Fix rename of H7 RM0455 OCTOSPI peripheral

- devices/common_patches/hdmi_cec.yaml
- devices/stm32f0x1.yaml
- devices/stm32f0x2.yaml
- devices/stm32f0x8.yaml
- devices/stm32f765.yaml
- devices/stm32h735.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
This applies to the H7, F0x{1,2,8}, F7{6,7} which share identical register layouts.
> Add bit ranges to HDMI CEC registers

- devices/stm32l4r9.yaml
TIM3 and TIM4 work the same way in stm32l4r9 and stm32l4x6.
Since `stm32l4x6.yaml` contains these `_copy` and `_derive` lines, they should also be added to this yaml file.
Note that I've simply verified this empirically, with these lines added I can now use TIM3 and TIM4 to generate a PWM signal,
and that I don't fully comprehend the SVD files yet.
> devices/stm32l4r9.yaml: patch TIM3 and TIM4

- scripts/makehtml.py
Python3.8 and above [changed](https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/) the behavior of the multiprocessing module on macOS, resulting in variable scoping being tighter than on other platforms or versions.
As a simplified case, this code crashes on such a machine:
```python
import multiprocessing
def worker(local):
print(v)
if __name__ == "__main__":
v = "can i access this?"
with multiprocessing.Pool() as p:
devices = p.map(worker, [None])
```
This patch passes in the relevant variable into the worker in a different style to fix. I've tested this on linux and Mac platforms for regressions.
> Fix make html on macOS with python 3.8+

- devices/common_patches/h743_hrtim_common.yaml
- devices/common_patches/h74x_syscfg_pwrcr.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
Adding fixes to two fields on h743/h753 micros. These bugs were found by comparing against h747 svd files and verified to not be present on any other h7 micros (beyond those fixed in this PR).
ODEN should be 1-bit and have an enumeration. H747 had the correct bit width already; the oden patch is now applied to more devices.
BDMADR should be at 0x70, not 0x60.
> Fix Overdrive and BDMADR fields on h743/h753

- devices/common_patches/l4_gpio_ascr.yaml
- devices/common_patches/l4_gpio_ascr_brr.yaml
- devices/common_patches/l4_gpio_brr.yaml
- devices/stm32l4x1.yaml
- devices/stm32l4x2.yaml
- devices/stm32l4x3.yaml
- devices/stm32l4x5.yaml
Also corrects naming on L4x5 ADC `Mult` to `Dual` field, as per the reference manual, and adds prescaler field under ADC_CRR.
Fixes https://github.com/stm32-rs/stm32-rs/issues/342
> STM32L4xx: Add GPIOx ASCR & BRR registers

- devices/common_patches/h7_dmacr.yaml
I noticed that the patch to add a TRBUFF field to the H7 DMA SxCR registers also erroneously adds it to SxFCR, LIFCR, and HIFCR registers. This PR restricts it to only the SxCR registers.
It's not much of an issue since the incorrect fields are easily ignorable, but it is also easily fixable.
> Change H7 DMA CR patch to only include SxCR registers

- devices/stm32h735.yaml
The SVD files in this repo don't include timers TIM23 and TIM24 for the RM0468-based chips (H730, H723, H725, H733, H735). There is an updated SVD that someone from STM posted [here](https://community.st.com/s/question/0D53W00000cyEKvSAM/bug-stm32cubeide-missing-tim23-and-tim24-in-sfrs-window), which just adds the lines:
```
<peripheral derivedFrom="TIM2">
<name>TIM23</name>
<baseAddress>0x4000E000</baseAddress>
<interrupt>
<name>TIM23</name>
<description>TIM23 global interrupt</description>
<value>161</value>
</interrupt>
</peripheral>
<peripheral derivedFrom="TIM2">
<name>TIM24</name>
<baseAddress>0x4000E400</baseAddress>
<interrupt>
<name>TIM24</name>
<description>TIM24 global interrupt</description>
<value>162</value>
</interrupt>
</peripheral>
```
As far as I can tell, the changes I …
> Add timers TIM23 and TIM24 to stm32h735

- devices/common_patches/g0_flash.yaml
- devices/stm32g030.yaml
- devices/stm32g031.yaml
- devices/stm32g041.yaml
- devices/stm32g070.yaml
- devices/stm32g071.yaml
- devices/stm32g081.yaml
- devices/stm32g0b1.yaml
- devices/stm32g0c1.yaml
See reference manual for [STM32G0x0](https://www.st.com/resource/en/reference_manual/rm0454-stm32g0x0-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) and [STM32G0x1](https://www.st.com/resource/en/reference_manual/rm0444-stm32g0x1-advanced-armbased-32bit-mcus-stmicroelectronics.pdf). Both define FLASH_WRP1AR etc as read-write (but read-only in the SVD). STM32G0x1 defines FLASH_SECR as read-write (but read-only in the SVD). The STM32G0x0 doesn't have a FLASH_SECR register.
> Make FLASH_WRP??R and FLASH_SECR writable

- devices/stm32f301.yaml
- devices/stm32f3x4.yaml
The f301 is the only device in the F3 family, which has the field name
wrong. In the datasheet [RM0366] 12.5.3 `JADSTP` is also used.
[RM0366]: https://www.st.com/resource/en/reference_manual/dm00094350.pdf
> F301: Add missing P to JADST

- peripherals/adc/adc_v3.yaml
`ADDIS`, as `ADEN`, is a signal to the ADC peripheral to change it's
state. Both signals have to be "1" to change the state.
In case of `ADDIS` it will be only reset to "0", after the state has
successfully changed.
The procedure of disabling is the same between `stm32f303xc` (RM0316
15.3.10), where I've noticed the bug, and `stm32h7x3` (RM0443 25.4.9),
for which this code was initially committed, so I assume this affects
every device using the `adc_v3.yaml`.
> Fix ADC disable

- CHANGELOG.md
- devices/common_patches/usb_otg/otg_fs_fixes_v1.yaml
Hi, these are some issues I noticed when I was developing my usb host crate for the stm32f411.
> stm32f411 otg fixes

- devices/stm32f302.yaml
This matches other chips in the F30x lineage and is also how the reference manual calls it.
cc https://github.com/stm32-rs/stm32f3xx-hal/pull/318, where the inconsistent name required some extra `#[cfg]`s
> F302: rename `DAC` to `DAC1`

- devices/common_patches/f4_add_UART_GTPR.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
Currently, the F413 UART peripheral is a copy of its USART definition, whereas all of the other F4xx family use a separate independent definition for the UART peripheral (the independent definition doesn't include USART-specific fields which are not present in the UART peripheral).  Fix by using the F405 UART definition on the F413.
All F4xx UARTs support IrDA mode, which utilises the PSC fields of the GTPR register.  This field is missing in the UART definition (except F413 - see above) across the F4 family (presence and correct operation of the GTPR PSC field was verified by the author on F429 and F446 microcontrollers).
n.b. The other GTPR field (GT) appears to be specific to SmartCard mode - which is a USART-only feature, not supported on UART according to the reference manual, so the …
> f4xx: UART fix missing Guard Time and Prescaler Register, f413 UART should include USART-only fields.

- CHANGELOG.md
- devices/common_patches/g4_rcc.yaml
In peripheral registers overview table this is correctly
listed as RNGSMEN, only in detailed register description
it says RNGEN which seems incorrect (as all fields in the register
use `SMEN` suffix).
Comment also suggets that this is likely an error.
> g4 RCC Remove RNGSMEN -> RNGEN

- devices/stm32g070.yaml
The STM32G070 does not have the VREFBUF registers, but it does have SYSCFG. The SVD seems to correspond to the documentation with regards to SYSCFG.
Hence we should simply add SYSCFG instead of deleting it.
> Add SYSCFG to stm32g070

- devices/common_patches/f7_tim.yaml
When writing to  `CNT`/`ARR`/`CCR%s` single-field registers via `bits()`, it requires the use of unsafe for timers 9 to 14.
This PR allows to use safe `bits()` writing just like the other timers
> F7/tim: access to bits() without unsafe for single-field registers

- devices/common_patches/usb_otg/otg_fs_fixes_v1.yaml
- devices/stm32f215.yaml
These devices have OTG_FS with CID 0x0000 1200 (same as F401), and the SVD files seem to have the same bugs as F401/F411 SVD files.
> Apply OTG_FS v1 fixes to F215/F217

- CHANGELOG.md
- devices/common_patches/h7_dualcore_flash.yaml
See RM0399 Rev 3 Table 19. These mirrored registers are present on other H7 parts
Including these registers changes the svd2rust access style for bank2, from a public member to a method that returns a reference. This makes it consistent with other H7 parts
> H7 flash: Add registers that are mirrored between banks for rm0399

- devices/stm32l562.yaml
This PR fixes two issues with the STM32L562's SVD files. In particular the DMA registers CCR registers only included the correct fields on the first register. This PR fixes that.
It also merges the GTZC VCTR into an array, rather than individual fields.
> Fix various issues with STM32L562

- devices/common_patches/tim/tim2_itr1_rmp.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
These values are from STMicro RM0090, 18.4.19:
This reference manual covers "STM32F405/415, STM32F407/417, STM32F427/437 and STM32F429/439", so it's likely that this change could apply to those other devices as well. I don't have one to test, though, so defer to maintainers' preferences here. ~~Happy to extract this to a common patch if folks are happy with that approach.~~ EDIT: I've pushed 3a7e8e4 which does just this.
> Add enumerated values for STM32F405/415/407/417/427/437/429/439 TIM2 ITR1_RMP

- devices/common_patches/f41x_bdcr_lsemod.yaml
- devices/stm32f410.yaml
- devices/stm32f411.yaml
- devices/stm32f412.yaml
According to this design guide,
https://www.st.com/resource/en/application_note/an2867-oscillator-design-guide-for-stm8afals-stm32-mcus-and-mpus-stmicroelectronics.pdf#page=25,
as well the reference manuals for those MCUs
(https://www.st.com/resource/en/reference_manual/rm0401-stm32f410-advanced-armbased-32bit-mcus-stmicroelectronics.pdf,
https://www.st.com/resource/en/reference_manual/rm0383-stm32f411xce-advanced-armbased-32bit-mcus-stmicroelectronics.pdf,
https://www.st.com/resource/en/reference_manual/rm0402-stm32f412-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
the LSEMOD bit should be available.
> Add missing BDCR LSEMOD field for STM32F410/11/12

- devices/common_patches/adc_common_group_name.yaml
- devices/common_patches/l4_adc_common.yaml
- devices/common_patches/wb_adc_common.yaml
- devices/stm32f215.yaml
- devices/stm32f217.yaml
- devices/stm32f401.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f410.yaml
- devices/stm32f411.yaml
- devices/stm32f412.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
- devices/stm32f730.yaml
- devices/stm32f745.yaml
- devices/stm32f750.yaml
- devices/stm32f765.yaml
- devices/stm32f7x2.yaml
- devices/stm32f7x3.yaml
- devices/stm32f7x6.yaml
- devices/stm32f7x7.yaml
- devices/stm32f7x9.yaml
- devices/stm32l4r9.yaml
- devices/stm32l4x5.yaml
- devices/stm32l4x6.yaml
- devices/stm32l552.yaml
- devices/stm32l562.yaml
In the https://github.com/tinygo-org/stm32-svd project, it depends this project and generates types by the peripheral's groupName. Because the ADC_Common's groupName is ADC, it can't generate the types ADC and ADC_Common correctly. I want to change the ADC_Common's groupName to ADC to make it work fine.  See https://github.com/tinygo-org/tinygo/pull/2717 , https://github.com/tinygo-org/stm32-svd/pull/7 , but those are not good way.
I checked the generated rust code, it's not changed after apply this change and run make, seems it doesn't depend groupName. So can you accept this PR?
> Change the groupName of ADC_Common from ADC to ADC_Common

- devices/common_patches/sai/sai_v1.yaml
- devices/common_patches/sai/sai_v2.yaml
> Set SAI FSDEF to read-write to match described usage, despite all the RMs calling it read-only

- .github/workflows/gh-pages.yaml
Hopefully this means we can stop using the `gh-pages` branch which takes a long time to clone whenever you update a local checkout.
> Try new github pages deployment action

- README.md
Update local build instructions to match the configuation used in CI. The current instructions are broken for master.
svd2rust 0.25.1 is used since #769, and CI uses the Rust builds of svdtools
> Update local build instructions in README

- devices/stm32f401.yaml
- devices/stm32f411.yaml
Just changing the order of the fixes.
adc_v2_smpr.yml fix adds fields to the registers (original svd incorrectly had only one field).
adc_v2.yml adds enumeration to the smpr* fields in the adc1.smprX registers.
We need to first add fields  and then add enumeration to have enumerations on all fields. In the current order only one field has enumeration. When we change order all fields have enumerations.
This probably should be done on all other devices with the [adc fix](https://github.com/stm32-rs/stm32-rs/pull/460/commits/3f1e2e1879a8d16bb55c5c1197694f63f1da5c92).
> add enum to stm32f411 adc1 smpr register

- .github/workflows/ci.yaml
- .github/workflows/nightlies.yaml
`actions-rs` appears to be unmaintained: https://github.com/actions-rs/toolchain/issues/216
> ci: fix node 12 deprecation warnings

- .gitattributes
On cygwin you get errors because the scripts have mixed line endings, e.g.
```
Hydra on DESKTOP-H1JUK44 in /cygdrive/d/Users/Hydra/Documents/dev/projects/stm32-rs/stm32-rs/svd (master)
$ ./extract.sh
./extract.sh: line 2: syntax error near unexpected token `$'do\r''
'/extract.sh: line 2: `for f in vendor/*.zip; do
```
See also:
https://git-scm.com/docs/gitattributes
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows
For this repo, I use `autocrlf=auto`, as per the recommendations.
This PR will prevent future accidental line endings making their way into the repo for all .sh files.
> Add .gitattributes file to fix script line endings.

- devices/stm32f413.yaml
Hi, I2S*ext were missing from f413 pac, so i added them by deriving it from SPI1. I didn't add their interrput because they are already defined by SPI peripheral. 
Is it relevant to have the interrupt definition on the right peripheral ? When running `svdtools interrupts ../svd/stm32f413.svd.patched` I see many interrupt with the right description, but defined on the wrong peripheral
> add missing I2S*ext peripherals on f413

- devices/stm32wb55.yaml
Seems like TIM2 could've benefited from the `tim2_32bit` patch, looks like someone started it but never quite finished (or maybe the `tim2_32bit` patch didn't exist back then?)
Either way, this PR does exactly what the name suggests
> Apply TIM2 32-bit patch to STM32WB55

- scripts/makehtml.py
The differences between `{DIEP,DOEP}0` and `{DIEP,DOEP}%s` in #768 resulted in makehtml returning a `ValueError` for DIEP0.  The contents of this PR doesn't fix it, just makes it easier to debug for the future.
CC @burrbull
---
The simple hack-fix is to do this:
```python
if get_string(node, "name") in ("DIEP0", "DOEP0"):
return []
else:
raise ValueError("Can't process cluster '{}' without dim_index".format(
get_string(node, "name")
))
```
Perhaps the ValueError should be removed and replaced with `return []` as a long-term fix?  This makes it so DIEP0/DOEP0 get handled separately in the HTML output.  Can change this PR or open another if that is a desirable solution.
> makehtml: improve expand_cluster ValueError

- devices/common_patches/ethernet/f4_f7.yaml
- devices/stm32f217.yaml
- devices/stm32f405.yaml
- devices/stm32f407.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f469.yaml
- devices/stm32f745.yaml
- devices/stm32f750.yaml
- devices/stm32f765.yaml
- devices/stm32f7x7.yaml
- devices/stm32f7x9.yaml
- peripherals/eth/eth_ptp_ppsfreq.yaml
Remove the `TSSO` and `TSTTR` fields from `PTPPPSCR` on `f4` and `f7` as they don't actually exist on that register and add `PPSFREQ` field to `PTPPPSCR` on `f4` and `f7` since that field is missing from the SVDs.
Add variants for the `PPSFREQ` field for `f2`, `f4`, and `f7`
Fixes #801
Reference:
`stm32f207` and `stm32f217`, see [RM0033, page 939](https://www.st.com/resource/en/reference_manual/cd00225773-stm32f205xx-stm32f207xx-stm32f215xx-and-stm32f217xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
`stm32f405`, `stm32f407`, `stm32f417`, and `stm32f427`, and `stm32f429`, see [RM0090, page 1222](https://www.st.com/resource/en/reference_manual/dm00031020-stm32f405-415-stm32f407-417-stm32f427-437-and-stm32f429-439-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf) (as a …
> Fix `PTPPPSCR` on `stm32f4` and `stm32f7`, add variants for `PTPPPSCR:PPSFREQ` on `stm32f2`, `stm32f4`, `stm32f7`

- devices/stm32l4x6.yaml
I copied a patch from l4x5 and removed some code that the l4x5 yaml doesn't have.  I've compiled it with stm32-hal and it seems to recognize all the filters and channels like with l4x5.  However I don't really know what I'm doing so let me know what you think.
>  L4x6 missing registers for dfsdm filter1 #760 

- devices/stm32l4x5.yaml
For some reason https://github.com/stm32-rs/stm32-rs/issues/572 was not fixed.
This request adds the missing CRSEN bit to the L4x5 devices.
> Fixes missing CRSEN bit for L4x5 devices

- CHANGELOG.md
- devices/stm32f410.yaml
- devices/stm32f413.yaml
- devices/stm32f427.yaml
- devices/stm32f429.yaml
- devices/stm32f446.yaml
- devices/stm32f469.yaml
- peripherals/dac/dac_f410.yaml
- peripherals/dac/dac_f4_2ch.yaml
- peripherals/dac/dac_wavegen.yaml
remove Channel 2 from STM32F410, correct variants of `TSEL?`(TIM3 -> TIM8, TIM15 -> TIM5, add TIM4), merge `WAVE` field and `MAMP`field
> fix DAC peripheral for stm32f4

- CHANGELOG.md
- devices/common_patches/rng/h735.yaml
- devices/common_patches/rng/l4+.yaml
- devices/stm32h735.yaml
A register and several bits in the control register were missing from the SVD file. These missing registers were very similar to those in the l4+, so I edited those patches to make it work.
> Update stm32h735 RNG.

- CHANGELOG.md
- devices/common_patches/h5.yaml
- devices/common_patches/rcc/h5.yaml
- devices/common_patches/rcc/h503.yaml
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/rcc/rcc_h5.yaml
- peripherals/rcc/rcc_h503.yaml
- peripherals/rcc/rcc_h7.yaml
- peripherals/rcc/rcc_h7_revision_v.yaml
- peripherals/rcc/rcc_v3.yaml
- peripherals/rcc/rcc_v3_bdcr_ext.yaml
- peripherals/rcc/rcc_v3_cfgr.yaml
- peripherals/rcc/rcc_v3_cfgr1_cfgr2.yaml
- peripherals/rcc/rcc_v3_cr_hseext.yaml
- peripherals/rcc/rcc_v3_csr.yaml
- peripherals/rcc/rcc_v3_d3amr_srdamr.yaml
- peripherals/rcc/rcc_v3_gsr.yaml
- peripherals/rcc/rcc_v3_hsicfgr.yaml
This is exhaustive for the H503 chip, but doesn't include all field definitions for the H562/563/573 processors, which have quite a few more registers, particularly related to security features.
It also fixes register and field names for the H5 family that are inconsistent between the SVD and the Reference manuals.
It also includes some light refactoring of some fields common to the H5 and H7 families.
> Add RCC definitions for H5 family

- CHANGELOG.md
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- devices/stm32h735.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
- peripherals/spi/spi_v3_base.yaml
- peripherals/spi/spi_v3_cfg1_bpass.yaml
- peripherals/spi/spi_v3_cfg1_udrdet.yaml
- peripherals/spi/spi_v3_cfg1_udrdet_udrcfg.yaml
- peripherals/spi/spi_v3_tser.yaml
The SPI peripheral is largely shared with the H7 family, except that UDRCFG is 2 bits instead of 1 bit on the H7 family. This refactors the SPI field definitions slightly to account for this slight difference (moving the difference into a specific file only included on the H7 devices). Ultimately, the H7 definitions should be unchanged, and the H5 definitions should be complete for the whole family.
> Add SPI definitions for H5 family

- CHANGELOG.md
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/pwr/pwr_h5.yaml
The PWR peripheral for the H5 family is largely specific to that family, so this adds an H5 specific set of register definitions
> Add PWR definitions for H5 family

- CHANGELOG.md
- devices/common_patches/h5.yaml
- devices/common_patches/sbs/sbs.yaml
- devices/stm32h503.yaml
- peripherals/sbs/sbs.yaml
The SBS peripheral is new for the M33 series of processors (replacing SYSCFG). This adds the definitions relevant for the H5 family.
> Add SBS peripheral for H5 family

- CHANGELOG.md
- devices/common_patches/h5.yaml
- devices/common_patches/usart/merge_CR3_WUS_field.yaml
- devices/common_patches/usart/rename_CR1_ISR_enabled_disabled.yaml
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/usart/_v2_ABC_common.yaml
- peripherals/usart/_v2_AB_common.yaml
- peripherals/usart/fifoen_common.yaml
- peripherals/usart/fifoen_usart.yaml
- peripherals/usart/prescalar.yaml
- peripherals/usart/smartcard.yaml
- peripherals/usart/sync_slave.yaml
- peripherals/usart/usart_fifoen.yaml
- peripherals/usart/usart_prescalar.yaml
- peripherals/usart/usart_smartcard.yaml
- peripherals/usart/usart_sync_slave.yaml
- peripherals/usart/usart_wl.yaml
This does some light refactoring of the UART organization, adds some missing fields (for multiple processor families), and fixes some naming for the H5 family specifically.
> Add UART definitions for H5 family

- CHANGELOG.md
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/i2c/i2c_v2_cr1_fmp_addraclr_stopfaclr.yaml
The H5 I2C is largely the same as the existing v2 definition. Additional fields were added to a supplemental yaml.
> Add I2C for H5 family

- CHANGELOG.md
- devices/common_patches/h5.yaml
- devices/common_patches/h56x_h57x.yaml
- devices/common_patches/tim/tim_ccm_ext.yaml
- devices/common_patches/tim/tim_ccr.yaml
- devices/common_patches/tim/tim_dither.yaml
- devices/common_patches/tim/tim_mms_ts_sms_ext.yaml
- devices/common_patches/tim/tim_uifremap.yaml
- devices/stm32f301.yaml
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/tim/tim1_advanced.yaml
- peripherals/tim/tim2345_16bit.yaml
- peripherals/tim/tim2345_mixed.yaml
- peripherals/tim/tim2_32bit.yaml
- peripherals/tim/tim2_common.yaml
- peripherals/tim/tim6.yaml
- peripherals/tim/tim6_base.yaml
- peripherals/tim/tim6_dither.yaml
- peripherals/tim/tim_common_ext.yaml
- peripherals/tim/tim_dither.yaml
- peripherals/tim/tim_mms_ts_sms.yaml
- peripherals/tim/tim_uifremap.yaml
- peripherals/tim/v2/ccm_1_8.yaml
- peripherals/tim/v2/ccm_common.yaml
- peripherals/tim/v2/ccm_extended.yaml
This does some light refactoring of the timer field definitions to account for similarities and differences between the H5 family and other families, and provides full definitions for Timers 1-8, which are common to the H5 family. Note: It does not provide any definitions for TIM1x found on the larger H562, H563 and H573 chips.
> Add definitions for TIM1-8 for H5 family

- CHANGELOG.md
- devices/common_patches/h5.yaml
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/iwdg/iwdg.yaml
- peripherals/iwdg/iwdg_ewcr.yaml
- peripherals/iwdg/iwdg_pr_ext.yaml
- peripherals/iwdg/iwdg_sr.yaml
- peripherals/iwdg/iwdg_sr_ext.yaml
Modifies some common IWDG field definitions to account for the larger fields on the H5 family, fixes some register definitions for the H5 family and adds the definitions for all H5 processors.
> Add IWDG for H5 family

- CHANGELOG.md
- devices/stm32h503.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/crs/crs.yaml
The CRS peripheral was missing from stm32-rs (I'm not sure whether or not it's new with the H5 family), so this adds the definitions relevant to the H5 family, and includes it in the H5 PAC.
> Add CRS peripheral and add to H5 family

- CHANGELOG.md
- devices/common_patches/gpio/h7_ijk.yaml
- devices/common_patches/gpio/h7_jk.yaml
- devices/common_patches/gpio/h7_reset_values_common.yaml
- devices/stm32h735.yaml
- devices/stm32h743.yaml
- devices/stm32h743v.yaml
- devices/stm32h747cm4.yaml
- devices/stm32h747cm7.yaml
- devices/stm32h753.yaml
- devices/stm32h753v.yaml
- devices/stm32h7b3.yaml
Currently, all GPIO peripherals are derived from GPIOA for the STM32H7 devices.
However, the reset values of some registers are different for GPIOA and GPIOB
compared to the other GPIO's.
This PR fixes this issue.
> Fix reset values for STM32H7 GPIO

- CHANGELOG.md
- devices/stm32h735.yaml
Add I2C5 according to the latest SVD file:
```
<peripheral derivedFrom="I2C1">
<name>I2C5</name>
<baseAddress>0x40006400</baseAddress>
<interrupt>
<name>I2C5_EV</name>
<description>I2C5 event interrupt</description>
<value>157</value>
</interrupt>
<interrupt>
<name>I2C5_ER</name>
<description>I2C5 error interrupt</description>
<value>158</value>
</interrupt>
</peripheral>
```
> Add I2C5 to stm32h735.yaml

- CHANGELOG.md
- devices/stm32u535.yaml
- devices/stm32u545.yaml
- devices/stm32u575.yaml
- devices/stm32u585.yaml
- devices/stm32u595.yaml
- devices/stm32u599.yaml
- devices/stm32u5a5.yaml
- devices/stm32u5a9.yaml
- peripherals/rcc/rcc_u5.yaml
Originally part of #974.
This is probably the largest of the bunch, but mostly just because I included all the `DivXXX` enum values most of the time. I'm not sure if there's a general rule when to do it and when not (e.g. PLLxN I didn't do because it went up to 512), so let me know if there's any you would prefer also not having all written out like that.
> STM32U5: Add RCC peripheral

- CHANGELOG.md
- devices/common_patches/flash/g4_dual_bank.yaml
- devices/stm32g471.yaml
- devices/stm32g473.yaml
- devices/stm32g474.yaml
- devices/stm32g483.yaml
- devices/stm32g484.yaml
- peripherals/flash/flash_g4_dual_bank.yaml
This adds the missing dual bank flash related fields to stm32g4 devices:
* stm32g471
* stm32g473
* stm32g474
* stm32g483
* stm32g484
> Add dual bank related fields to stm32g4 cat 3 devices

- CHANGELOG.md
- devices/common_patches/u5.yaml
- devices/stm32u535.yaml
- devices/stm32u545.yaml
- devices/stm32u575.yaml
- devices/stm32u585.yaml
- devices/stm32u595.yaml
- devices/stm32u599.yaml
- devices/stm32u5a5.yaml
- devices/stm32u5a9.yaml
- peripherals/pwr/pwr_u5.yaml
Not quite ready yet - there are 4 registers that aren't in any SVD files, so I'll probably have to manually check on which devices they are available...
(FORCE_USBPWR, JPEGRAMPDS, VDD11USBDIS and SRAM6PDSx, see last lines of pwr_u5.yaml)
> STM32U5: Add PWR peripheral

- CHANGELOG.md
- peripherals/iwdg/iwdg.yaml
to make variant name more clear
> rename IWDG_KR KEY field variants

- CHANGELOG.md
- devices/common_patches/adc/u5.yaml
- devices/common_patches/adc/u5_extra_adc12_fields.yaml
- devices/common_patches/adc/u5_vsensesel.yaml
- devices/stm32u535.yaml
- devices/stm32u545.yaml
- devices/stm32u575.yaml
- devices/stm32u585.yaml
- devices/stm32u595.yaml
- devices/stm32u599.yaml
- devices/stm32u5a5.yaml
- devices/stm32u5a9.yaml
- peripherals/adc/adc_u5.yaml
- peripherals/adc/adc_u5_dual.yaml
Originally part of #974.
Will double-check the cycle count numbers, trigger identifiers etc. with the datasheet again tomorrow since I haven't touched this code in quite some time.
> STM32U5: Add ADC peripheral

- CHANGELOG.md
- devices/stm32g4a1.yaml
> G4A1 - Add missing FDCAN2, rename USB peripheral

- CHANGELOG.md
- devices/stm32g491.yaml
- devices/stm32g4a1.yaml
I just had a closer look at `devices/stm32g491.yaml` and  `devices/stm32g4a1.yaml` they seem to have diverged quite a bit. However looking in the [RM](https://www.st.com/resource/en/reference_manual/rm0440-stm32g4-series-advanced-armbased-32bit-mcus-stmicroelectronics.pdf#page=75) they are even in the same column under available peripherals so should be pretty much identical, I think, with AES being the only difference.
Also adds TIM20 to both devices
> Unify g49a and g4a1

- CHANGELOG.md
- devices/stm32mp153.yaml
- devices/stm32mp157.yaml
Previously, this bitfield was created with read-only access, though it's supposed to be writable by software. Fixes #1010.
> stm32mp1: Fix RCC.RCC_BDCR.DIGBYP Access

- CHANGELOG.md
- devices/common_patches/mpu_unprefix_registers.yaml
- devices/stm32mp153.yaml
- devices/stm32mp157.yaml
As promised in the discourse captured on #1011, strip the prefixes from the registers of nearly all the peripherals on these parts.
> stm32mp15x: Strip register prefixes

- .github/workflows/mmaps_pr_compare.yaml
- CHANGELOG.md
- devices/stm32f103.yaml
Drops `CAN2`, renames all occurrences of `CAN1` to `CAN` to match `RCC`
See also https://github.com/stm32-rs/stm32-rs/pull/731#issuecomment-1113274361
CC @burrbull
> only a single CAN on F103

- Makefile
- scripts/makesettings.sh
The Makefile invocation for creating the settings files isn't compatible with macOS's version of make. This moves the logic into separate script and calls the script from the Makefile.
> Move settings creation into shell script to fix invocation on macOS

- CHANGELOG.md
- devices/common_patches/rcc/h56x_h57x.yaml
- devices/stm32h562.yaml
- devices/stm32h563.yaml
- devices/stm32h573.yaml
- peripherals/rcc/rcc_h5.yaml
- peripherals/rcc/rcc_h503.yaml
- peripherals/rcc/rcc_h563_h573.yaml
- peripherals/rcc/rcc_h56x_h57x.yaml
This adds RCC register patches and field definitions for all processors covered by RM0481 (this includes H523/533 processors, but these haven't yet been added as products, yet).
> H5: Add RCC register patches and field definitions for the for H56x/H573 processors

- CHANGELOG.md
- devices/stm32g0b1.yaml
Currently it is incorrectly implemented as 32-bit timer.
> Make TIM4 16-bit on stm32g0b1

- CHANGELOG.md
- devices/fields/afio/derive.yaml
- devices/fields/exti/exti_g0.yaml
- devices/fields/syscfg/derive.yaml
- devices/fields/syscfg/f4/syscfg_f401_f411.yaml
- devices/fields/syscfg/f4/syscfg_f405.yaml
- devices/fields/syscfg/f4/syscfg_f410.yaml
- devices/fields/syscfg/f4/syscfg_f412.yaml
- devices/fields/syscfg/f4/syscfg_f413_f423.yaml
- devices/fields/syscfg/f4/syscfg_f415_f407_f417.yaml
- devices/fields/syscfg/f4/syscfg_f427_f437_f429_f439.yaml
- devices/fields/syscfg/f4/syscfg_f446.yaml
- devices/fields/syscfg/f4/syscfg_f469_f479.yaml
- devices/fields/syscfg/syscfg_f0x128.yaml
- devices/fields/usb/g0_usb.yaml
- devices/stm32f0x0.yaml
- devices/stm32f100.yaml
- devices/stm32f101.yaml
- devices/stm32f102.yaml
- devices/stm32f103.yaml
- devices/stm32f107.yaml
Marking USB bits to avoid accidental flips.
EXTI only had human-readable enums in CR1 until this change.
> Update field definitions in USB ISTR, USB CHEPR and EXTICR

- CHANGELOG.md
- devices/patches/rng/h503.yaml
- devices/stm32h503.yaml
This is missing in the SVD, but documented in RM0492
> H503: Add missing RNG register definition

- devices/fields/rcc/v3/h5.yaml
- devices/fields/rcc/v3/h503.yaml
- devices/fields/rcc/v3/h56x_h57x.yaml
From what I can tell only [H503](https://stm32-rs.github.io/stm32-rs/STM32H503.html#RCC:CCIPR4:USBSEL) should have PLL2Q as option for USBSEL with value 0x2. The rest of the timers should be [PLL3Q](https://stm32-rs.github.io/stm32-rs/STM32H533.html#RCC:CCIPR4:USBSEL)
> USBSEL 0x2: PLL2Q for H503, PLL3Q for rest of H5

- CHANGELOG.md
- devices/patches/flash/h7_dualcore.yaml
* [H747_CM7 - KEYR](https://stm32-rs.github.io/stm32-rs/STM32H747_CM7.html#FLASH:KEYR%20[1]:KEYR)
* [H743 - KEY1R](https://stm32-rs.github.io/stm32-rs/STM32H743.html#FLASH:KEYR%20[1]:KEY1R)
> Flash H7 - Make naming consistent with single core devices

- CHANGELOG.md
- devices/stm32f745.yaml
- devices/stm32f746.yaml
- devices/stm32f750.yaml
- devices/stm32f756.yaml
dbg_common.yaml might also be useful, but would require renaming the freeze registers like in
devices/patches/dbgmcu/l4_apb_fzr_rename.yaml
> STM32F745: pull in dbg_trace fields

- CHANGELOG.md
- devices/stm32f100.yaml
In the rm0041 manual, the reset value of the TIM12_ARR register is given as 0xFFFF, not 0x0000.
> modify reset value TIM12_ARR
